# DO NOT EDIT - generated by xdr_parser.py from probe1_xdr.x
# Apply changes to probe1_xdr.x instead.
import sys,os
from . import probe1_xdr_const as const
class probe_time1:
    # XDR definition:
    # struct probe_time1 {
    #     uint seconds;
    #     uint nseconds;
    # };
    def __init__(self, seconds=None, nseconds=None):
        self.seconds = seconds
        self.nseconds = nseconds

    def __repr__(self):
        out = []
        if self.seconds is not None:
            out += ['seconds=%s' % repr(self.seconds)]
        if self.nseconds is not None:
            out += ['nseconds=%s' % repr(self.nseconds)]
        return 'probe_time1(%s)' % ', '.join(out)
    __str__ = __repr__

class probe_op1:
    # XDR definition:
    # struct probe_op1 {
    #     uint po_op;
    #     string po_name<>;
    #     uhyper po_calls;
    #     uhyper po_errors;
    #     uhyper po_max_duration;
    #     uhyper po_total_duration;
    #     uhyper po_bucket_1ms;
    #     uhyper po_bucket_10ms;
    #     uhyper po_bucket_100ms;
    #     uhyper po_bucket_1s;
    #     uhyper po_bucket_10s;
    #     uhyper po_bucket_rest;
    #     uhyper po_median_ns;
    #     uhyper po_p90_ns;
    #     uhyper po_p99_ns;
    #     uhyper po_p999_ns;
    #     uhyper po_min_ns;
    #     uhyper po_max_ns;
    #     uhyper po_mean_ns;
    # };
    def __init__(self, po_op=None, po_name=None, po_calls=None, po_errors=None, po_max_duration=None, po_total_duration=None, po_bucket_1ms=None, po_bucket_10ms=None, po_bucket_100ms=None, po_bucket_1s=None, po_bucket_10s=None, po_bucket_rest=None, po_median_ns=None, po_p90_ns=None, po_p99_ns=None, po_p999_ns=None, po_min_ns=None, po_max_ns=None, po_mean_ns=None):
        self.po_op = po_op
        self.po_name = po_name
        self.po_calls = po_calls
        self.po_errors = po_errors
        self.po_max_duration = po_max_duration
        self.po_total_duration = po_total_duration
        self.po_bucket_1ms = po_bucket_1ms
        self.po_bucket_10ms = po_bucket_10ms
        self.po_bucket_100ms = po_bucket_100ms
        self.po_bucket_1s = po_bucket_1s
        self.po_bucket_10s = po_bucket_10s
        self.po_bucket_rest = po_bucket_rest
        self.po_median_ns = po_median_ns
        self.po_p90_ns = po_p90_ns
        self.po_p99_ns = po_p99_ns
        self.po_p999_ns = po_p999_ns
        self.po_min_ns = po_min_ns
        self.po_max_ns = po_max_ns
        self.po_mean_ns = po_mean_ns

    def __repr__(self):
        out = []
        if self.po_op is not None:
            out += ['po_op=%s' % repr(self.po_op)]
        if self.po_name is not None:
            out += ['po_name=%s' % repr(self.po_name)]
        if self.po_calls is not None:
            out += ['po_calls=%s' % repr(self.po_calls)]
        if self.po_errors is not None:
            out += ['po_errors=%s' % repr(self.po_errors)]
        if self.po_max_duration is not None:
            out += ['po_max_duration=%s' % repr(self.po_max_duration)]
        if self.po_total_duration is not None:
            out += ['po_total_duration=%s' % repr(self.po_total_duration)]
        if self.po_bucket_1ms is not None:
            out += ['po_bucket_1ms=%s' % repr(self.po_bucket_1ms)]
        if self.po_bucket_10ms is not None:
            out += ['po_bucket_10ms=%s' % repr(self.po_bucket_10ms)]
        if self.po_bucket_100ms is not None:
            out += ['po_bucket_100ms=%s' % repr(self.po_bucket_100ms)]
        if self.po_bucket_1s is not None:
            out += ['po_bucket_1s=%s' % repr(self.po_bucket_1s)]
        if self.po_bucket_10s is not None:
            out += ['po_bucket_10s=%s' % repr(self.po_bucket_10s)]
        if self.po_bucket_rest is not None:
            out += ['po_bucket_rest=%s' % repr(self.po_bucket_rest)]
        if self.po_median_ns is not None:
            out += ['po_median_ns=%s' % repr(self.po_median_ns)]
        if self.po_p90_ns is not None:
            out += ['po_p90_ns=%s' % repr(self.po_p90_ns)]
        if self.po_p99_ns is not None:
            out += ['po_p99_ns=%s' % repr(self.po_p99_ns)]
        if self.po_p999_ns is not None:
            out += ['po_p999_ns=%s' % repr(self.po_p999_ns)]
        if self.po_min_ns is not None:
            out += ['po_min_ns=%s' % repr(self.po_min_ns)]
        if self.po_max_ns is not None:
            out += ['po_max_ns=%s' % repr(self.po_max_ns)]
        if self.po_mean_ns is not None:
            out += ['po_mean_ns=%s' % repr(self.po_mean_ns)]
        return 'probe_op1(%s)' % ', '.join(out)
    __str__ = __repr__

class probe_program1:
    # XDR definition:
    # struct probe_program1 {
    #     uint pp_program;
    #     uint pp_version;
    #     uhyper pp_count;
    #     uhyper pp_replied_errors;
    #     uhyper pp_rejected_errors;
    #     uhyper pp_accepted_errors;
    #     uhyper pp_authed_errors;
    #     probe_op1 pp_ops<>;
    # };
    def __init__(self, pp_program=None, pp_version=None, pp_count=None, pp_replied_errors=None, pp_rejected_errors=None, pp_accepted_errors=None, pp_authed_errors=None, pp_ops=None):
        self.pp_program = pp_program
        self.pp_version = pp_version
        self.pp_count = pp_count
        self.pp_replied_errors = pp_replied_errors
        self.pp_rejected_errors = pp_rejected_errors
        self.pp_accepted_errors = pp_accepted_errors
        self.pp_authed_errors = pp_authed_errors
        self.pp_ops = pp_ops

    def __repr__(self):
        out = []
        if self.pp_program is not None:
            out += ['pp_program=%s' % repr(self.pp_program)]
        if self.pp_version is not None:
            out += ['pp_version=%s' % repr(self.pp_version)]
        if self.pp_count is not None:
            out += ['pp_count=%s' % repr(self.pp_count)]
        if self.pp_replied_errors is not None:
            out += ['pp_replied_errors=%s' % repr(self.pp_replied_errors)]
        if self.pp_rejected_errors is not None:
            out += ['pp_rejected_errors=%s' % repr(self.pp_rejected_errors)]
        if self.pp_accepted_errors is not None:
            out += ['pp_accepted_errors=%s' % repr(self.pp_accepted_errors)]
        if self.pp_authed_errors is not None:
            out += ['pp_authed_errors=%s' % repr(self.pp_authed_errors)]
        if self.pp_ops is not None:
            out += ['pp_ops=%s' % repr(self.pp_ops)]
        return 'probe_program1(%s)' % ', '.join(out)
    __str__ = __repr__

class STATS_GATHER1args:
    # XDR definition:
    # struct STATS_GATHER1args {
    #     uint psga_program;
    #     uint psga_version;
    # };
    def __init__(self, psga_program=None, psga_version=None):
        self.psga_program = psga_program
        self.psga_version = psga_version

    def __repr__(self):
        out = []
        if self.psga_program is not None:
            out += ['psga_program=%s' % repr(self.psga_program)]
        if self.psga_version is not None:
            out += ['psga_version=%s' % repr(self.psga_version)]
        return 'STATS_GATHER1args(%s)' % ', '.join(out)
    __str__ = __repr__

class STATS_GATHER1resok:
    # XDR definition:
    # struct STATS_GATHER1resok {
    #     probe_program1 psgr_program;
    # };
    def __init__(self, psgr_program=None):
        self.psgr_program = psgr_program

    def __getattr__(self, attr):
        return getattr(self.psgr_program, attr)

    def __repr__(self):
        out = []
        if self.psgr_program is not None:
            out += ['psgr_program=%s' % repr(self.psgr_program)]
        return 'STATS_GATHER1resok(%s)' % ', '.join(out)
    __str__ = __repr__

class STATS_GATHER1res:
    # XDR definition:
    # union STATS_GATHER1res switch(probe_stat1 psgr_status) {
    #     case PROBE1_OK:
    #         STATS_GATHER1resok psgr_resok;
    #     default:
    #         void;
    # };
    def __init__(self, psgr_status=None, psgr_resok=None):
        self.psgr_status = psgr_status
        self.psgr_resok = psgr_resok

    switch = property(lambda s: {const.PROBE1_OK:s.psgr_resok,}.get(s.psgr_status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.psgr_status is not None:
            out += ['psgr_status=%s' % const.probe_stat1.get(self.psgr_status, self.psgr_status)]
        if self.psgr_resok is not None:
            out += ['psgr_resok=%s' % repr(self.psgr_resok)]
        return 'STATS_GATHER1res(%s)' % ', '.join(out)
    __str__ = __repr__

class CONTEXT1resok:
    # XDR definition:
    # struct CONTEXT1resok {
    #     uhyper pcr_created;
    #     uhyper pcr_freed;
    #     uhyper pcr_active_cancelled;
    #     uhyper pcr_active_destroyed;
    #     uhyper pcr_cancelled_freed;
    #     uhyper pcr_destroyed_freed;
    # };
    def __init__(self, pcr_created=None, pcr_freed=None, pcr_active_cancelled=None, pcr_active_destroyed=None, pcr_cancelled_freed=None, pcr_destroyed_freed=None):
        self.pcr_created = pcr_created
        self.pcr_freed = pcr_freed
        self.pcr_active_cancelled = pcr_active_cancelled
        self.pcr_active_destroyed = pcr_active_destroyed
        self.pcr_cancelled_freed = pcr_cancelled_freed
        self.pcr_destroyed_freed = pcr_destroyed_freed

    def __repr__(self):
        out = []
        if self.pcr_created is not None:
            out += ['pcr_created=%s' % repr(self.pcr_created)]
        if self.pcr_freed is not None:
            out += ['pcr_freed=%s' % repr(self.pcr_freed)]
        if self.pcr_active_cancelled is not None:
            out += ['pcr_active_cancelled=%s' % repr(self.pcr_active_cancelled)]
        if self.pcr_active_destroyed is not None:
            out += ['pcr_active_destroyed=%s' % repr(self.pcr_active_destroyed)]
        if self.pcr_cancelled_freed is not None:
            out += ['pcr_cancelled_freed=%s' % repr(self.pcr_cancelled_freed)]
        if self.pcr_destroyed_freed is not None:
            out += ['pcr_destroyed_freed=%s' % repr(self.pcr_destroyed_freed)]
        return 'CONTEXT1resok(%s)' % ', '.join(out)
    __str__ = __repr__

class CONTEXT1res:
    # XDR definition:
    # union CONTEXT1res switch(probe_stat1 pcr_status) {
    #     case PROBE1_OK:
    #         CONTEXT1resok pcr_resok;
    #     default:
    #         void;
    # };
    def __init__(self, pcr_status=None, pcr_resok=None):
        self.pcr_status = pcr_status
        self.pcr_resok = pcr_resok

    switch = property(lambda s: {const.PROBE1_OK:s.pcr_resok,}.get(s.pcr_status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.pcr_status is not None:
            out += ['pcr_status=%s' % const.probe_stat1.get(self.pcr_status, self.pcr_status)]
        if self.pcr_resok is not None:
            out += ['pcr_resok=%s' % repr(self.pcr_resok)]
        return 'CONTEXT1res(%s)' % ', '.join(out)
    __str__ = __repr__

class TRACE_SET1args:
    # XDR definition:
    # struct TRACE_SET1args {
    #     probe_trace_category1 tsa_cat;
    #     uint tsa_set;
    # };
    def __init__(self, tsa_cat=None, tsa_set=None):
        self.tsa_cat = tsa_cat
        self.tsa_set = tsa_set

    def __repr__(self):
        out = []
        if self.tsa_cat is not None:
            out += ['tsa_cat=%s' % const.probe_trace_category1.get(self.tsa_cat, self.tsa_cat)]
        if self.tsa_set is not None:
            out += ['tsa_set=%s' % repr(self.tsa_set)]
        return 'TRACE_SET1args(%s)' % ', '.join(out)
    __str__ = __repr__

class TRACES_LIST1args:
    # XDR definition:
    # struct TRACES_LIST1args {
    #     probe_trace_category1 tla_cat;
    # };
    def __init__(self, tla_cat=None):
        self.tla_cat = tla_cat

    def __repr__(self):
        out = []
        if self.tla_cat is not None:
            out += ['tla_cat=%s' % const.probe_trace_category1.get(self.tla_cat, self.tla_cat)]
        return 'TRACES_LIST1args(%s)' % ', '.join(out)
    __str__ = __repr__

class probe_trace_list1:
    # XDR definition:
    # struct probe_trace_list1 {
    #     probe_trace_category1 ptl_cat;
    #     uint ptl_set;
    # };
    def __init__(self, ptl_cat=None, ptl_set=None):
        self.ptl_cat = ptl_cat
        self.ptl_set = ptl_set

    def __repr__(self):
        out = []
        if self.ptl_cat is not None:
            out += ['ptl_cat=%s' % const.probe_trace_category1.get(self.ptl_cat, self.ptl_cat)]
        if self.ptl_set is not None:
            out += ['ptl_set=%s' % repr(self.ptl_set)]
        return 'probe_trace_list1(%s)' % ', '.join(out)
    __str__ = __repr__

class TRACES_LIST1resok:
    # XDR definition:
    # struct TRACES_LIST1resok {
    #     probe_trace_list1 tlr_list<>;
    # };
    def __init__(self, tlr_list=None):
        self.tlr_list = tlr_list

    def __repr__(self):
        out = []
        if self.tlr_list is not None:
            out += ['tlr_list=%s' % repr(self.tlr_list)]
        return 'TRACES_LIST1resok(%s)' % ', '.join(out)
    __str__ = __repr__

class TRACES_LIST1res:
    # XDR definition:
    # union TRACES_LIST1res switch(probe_stat1 tlr_status) {
    #     case PROBE1_OK:
    #         TRACES_LIST1resok tlr_resok;
    #     default:
    #         void;
    # };
    def __init__(self, tlr_status=None, tlr_resok=None):
        self.tlr_status = tlr_status
        self.tlr_resok = tlr_resok

    switch = property(lambda s: {const.PROBE1_OK:s.tlr_resok,}.get(s.tlr_status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.tlr_status is not None:
            out += ['tlr_status=%s' % const.probe_stat1.get(self.tlr_status, self.tlr_status)]
        if self.tlr_resok is not None:
            out += ['tlr_resok=%s' % repr(self.tlr_resok)]
        return 'TRACES_LIST1res(%s)' % ', '.join(out)
    __str__ = __repr__

class HEARTBEAT1args:
    # XDR definition:
    # struct HEARTBEAT1args {
    #     uint hba_period;
    #     uint hba_period_set;
    # };
    def __init__(self, hba_period=None, hba_period_set=None):
        self.hba_period = hba_period
        self.hba_period_set = hba_period_set

    def __repr__(self):
        out = []
        if self.hba_period is not None:
            out += ['hba_period=%s' % repr(self.hba_period)]
        if self.hba_period_set is not None:
            out += ['hba_period_set=%s' % repr(self.hba_period_set)]
        return 'HEARTBEAT1args(%s)' % ', '.join(out)
    __str__ = __repr__

class HEARTBEAT1resok:
    # XDR definition:
    # struct HEARTBEAT1resok {
    #     uint hbr_period;
    # };
    def __init__(self, hbr_period=None):
        self.hbr_period = hbr_period

    def __repr__(self):
        out = []
        if self.hbr_period is not None:
            out += ['hbr_period=%s' % repr(self.hbr_period)]
        return 'HEARTBEAT1resok(%s)' % ', '.join(out)
    __str__ = __repr__

class HEARTBEAT1res:
    # XDR definition:
    # union HEARTBEAT1res switch(probe_stat1 hbr_status) {
    #     case PROBE1_OK:
    #         HEARTBEAT1resok hbr_resok;
    #     default:
    #         void;
    # };
    def __init__(self, hbr_status=None, hbr_resok=None):
        self.hbr_status = hbr_status
        self.hbr_resok = hbr_resok

    switch = property(lambda s: {const.PROBE1_OK:s.hbr_resok,}.get(s.hbr_status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.hbr_status is not None:
            out += ['hbr_status=%s' % const.probe_stat1.get(self.hbr_status, self.hbr_status)]
        if self.hbr_resok is not None:
            out += ['hbr_resok=%s' % repr(self.hbr_resok)]
        return 'HEARTBEAT1res(%s)' % ', '.join(out)
    __str__ = __repr__

class probe_io_context1:
    # XDR definition:
    # struct probe_io_context1 {
    #     probe_op_type1 pic_op_type;
    #     int pic_fd;
    #     uint pic_id;
    #     uint pic_xid;
    #     uhyper pic_buffer_len;
    #     uhyper pic_position;
    #     uhyper pic_expected_len;
    #     uhyper pic_state;
    #     uhyper pic_count;
    #     probe_time1 pic_action_time;
    # };
    def __init__(self, pic_op_type=None, pic_fd=None, pic_id=None, pic_xid=None, pic_buffer_len=None, pic_position=None, pic_expected_len=None, pic_state=None, pic_count=None, pic_action_time=None):
        self.pic_op_type = pic_op_type
        self.pic_fd = pic_fd
        self.pic_id = pic_id
        self.pic_xid = pic_xid
        self.pic_buffer_len = pic_buffer_len
        self.pic_position = pic_position
        self.pic_expected_len = pic_expected_len
        self.pic_state = pic_state
        self.pic_count = pic_count
        self.pic_action_time = pic_action_time

    def __getattr__(self, attr):
        return getattr(self.pic_action_time, attr)

    def __repr__(self):
        out = []
        if self.pic_op_type is not None:
            out += ['pic_op_type=%s' % const.probe_op_type1.get(self.pic_op_type, self.pic_op_type)]
        if self.pic_fd is not None:
            out += ['pic_fd=%s' % repr(self.pic_fd)]
        if self.pic_id is not None:
            out += ['pic_id=%s' % repr(self.pic_id)]
        if self.pic_xid is not None:
            out += ['pic_xid=%s' % repr(self.pic_xid)]
        if self.pic_buffer_len is not None:
            out += ['pic_buffer_len=%s' % repr(self.pic_buffer_len)]
        if self.pic_position is not None:
            out += ['pic_position=%s' % repr(self.pic_position)]
        if self.pic_expected_len is not None:
            out += ['pic_expected_len=%s' % repr(self.pic_expected_len)]
        if self.pic_state is not None:
            out += ['pic_state=%s' % repr(self.pic_state)]
        if self.pic_count is not None:
            out += ['pic_count=%s' % repr(self.pic_count)]
        if self.pic_action_time is not None:
            out += ['pic_action_time=%s' % repr(self.pic_action_time)]
        return 'probe_io_context1(%s)' % ', '.join(out)
    __str__ = __repr__

class probe_fd1:
    # XDR definition:
    # struct probe_fd1 {
    #     int pf_fd;
    #     uint pf_server_port;
    #     probe1_address_string pf_client;
    # };
    def __init__(self, pf_fd=None, pf_server_port=None, pf_client=None):
        self.pf_fd = pf_fd
        self.pf_server_port = pf_server_port
        self.pf_client = pf_client

    def __repr__(self):
        out = []
        if self.pf_fd is not None:
            out += ['pf_fd=%s' % repr(self.pf_fd)]
        if self.pf_server_port is not None:
            out += ['pf_server_port=%s' % repr(self.pf_server_port)]
        if self.pf_client is not None:
            out += ['pf_client=%s' % repr(self.pf_client)]
        return 'probe_fd1(%s)' % ', '.join(out)
    __str__ = __repr__

class IO_CONTEXTS_LIST1args:
    # XDR definition:
    # struct IO_CONTEXTS_LIST1args {
    #     int icla_fd;
    #     probe_op_type1 icla_op;
    #     uhyper icla_state;
    # };
    def __init__(self, icla_fd=None, icla_op=None, icla_state=None):
        self.icla_fd = icla_fd
        self.icla_op = icla_op
        self.icla_state = icla_state

    def __repr__(self):
        out = []
        if self.icla_fd is not None:
            out += ['icla_fd=%s' % repr(self.icla_fd)]
        if self.icla_op is not None:
            out += ['icla_op=%s' % const.probe_op_type1.get(self.icla_op, self.icla_op)]
        if self.icla_state is not None:
            out += ['icla_state=%s' % repr(self.icla_state)]
        return 'IO_CONTEXTS_LIST1args(%s)' % ', '.join(out)
    __str__ = __repr__

class IO_CONTEXTS_LIST1resok:
    # XDR definition:
    # struct IO_CONTEXTS_LIST1resok {
    #     probe_io_context1 iclr_pic<>;
    #     probe_time1 iclr_now;
    # };
    def __init__(self, iclr_pic=None, iclr_now=None):
        self.iclr_pic = iclr_pic
        self.iclr_now = iclr_now

    def __getattr__(self, attr):
        return getattr(self.iclr_now, attr)

    def __repr__(self):
        out = []
        if self.iclr_pic is not None:
            out += ['iclr_pic=%s' % repr(self.iclr_pic)]
        if self.iclr_now is not None:
            out += ['iclr_now=%s' % repr(self.iclr_now)]
        return 'IO_CONTEXTS_LIST1resok(%s)' % ', '.join(out)
    __str__ = __repr__

class IO_CONTEXTS_LIST1res:
    # XDR definition:
    # union IO_CONTEXTS_LIST1res switch(probe_stat1 iclr_status) {
    #     case PROBE1_OK:
    #         IO_CONTEXTS_LIST1resok iclr_resok;
    #     default:
    #         void;
    # };
    def __init__(self, iclr_status=None, iclr_resok=None):
        self.iclr_status = iclr_status
        self.iclr_resok = iclr_resok

    switch = property(lambda s: {const.PROBE1_OK:s.iclr_resok,}.get(s.iclr_status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.iclr_status is not None:
            out += ['iclr_status=%s' % const.probe_stat1.get(self.iclr_status, self.iclr_status)]
        if self.iclr_resok is not None:
            out += ['iclr_resok=%s' % repr(self.iclr_resok)]
        return 'IO_CONTEXTS_LIST1res(%s)' % ', '.join(out)
    __str__ = __repr__

class FD_INFOS_LIST1args:
    # XDR definition:
    # struct FD_INFOS_LIST1args {
    #     int fila_fd;
    # };
    def __init__(self, fila_fd=None):
        self.fila_fd = fila_fd

    def __repr__(self):
        out = []
        if self.fila_fd is not None:
            out += ['fila_fd=%s' % repr(self.fila_fd)]
        return 'FD_INFOS_LIST1args(%s)' % ', '.join(out)
    __str__ = __repr__

class FD_INFOS_LIST1resok:
    # XDR definition:
    # struct FD_INFOS_LIST1resok {
    #     probe_fd1 filr_pf<>;
    # };
    def __init__(self, filr_pf=None):
        self.filr_pf = filr_pf

    def __repr__(self):
        out = []
        if self.filr_pf is not None:
            out += ['filr_pf=%s' % repr(self.filr_pf)]
        return 'FD_INFOS_LIST1resok(%s)' % ', '.join(out)
    __str__ = __repr__

class FD_INFOS_LIST1res:
    # XDR definition:
    # union FD_INFOS_LIST1res switch(probe_stat1 filr_status) {
    #     case PROBE1_OK:
    #         FD_INFOS_LIST1resok filr_resok;
    #     default:
    #         void;
    # };
    def __init__(self, filr_status=None, filr_resok=None):
        self.filr_status = filr_status
        self.filr_resok = filr_resok

    switch = property(lambda s: {const.PROBE1_OK:s.filr_resok,}.get(s.filr_status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.filr_status is not None:
            out += ['filr_status=%s' % const.probe_stat1.get(self.filr_status, self.filr_status)]
        if self.filr_resok is not None:
            out += ['filr_resok=%s' % repr(self.filr_resok)]
        return 'FD_INFOS_LIST1res(%s)' % ', '.join(out)
    __str__ = __repr__

class probe_sb_info1:
    # XDR definition:
    # struct probe_sb_info1 {
    #     uhyper psi_id;
    #     opaque psi_uuid[16];
    #     string psi_path<>;
    #     probe_sb_lifecycle1 psi_state;
    #     probe_storage_type1 psi_storage_type;
    #     probe_auth_flavor1 psi_flavors<PROBE1_MAX_FLAVORS>;
    #     uhyper psi_bytes_max;
    #     uhyper psi_bytes_used;
    #     uhyper psi_inodes_max;
    #     uhyper psi_inodes_used;
    # };
    def __init__(self, psi_id=None, psi_uuid=None, psi_path=None, psi_state=None, psi_storage_type=None, psi_flavors=None, psi_bytes_max=None, psi_bytes_used=None, psi_inodes_max=None, psi_inodes_used=None):
        self.psi_id = psi_id
        self.psi_uuid = psi_uuid
        self.psi_path = psi_path
        self.psi_state = psi_state
        self.psi_storage_type = psi_storage_type
        self.psi_flavors = psi_flavors
        self.psi_bytes_max = psi_bytes_max
        self.psi_bytes_used = psi_bytes_used
        self.psi_inodes_max = psi_inodes_max
        self.psi_inodes_used = psi_inodes_used

    def __repr__(self):
        out = []
        if self.psi_id is not None:
            out += ['psi_id=%s' % repr(self.psi_id)]
        if self.psi_uuid is not None:
            out += ['psi_uuid=%s' % repr(self.psi_uuid)]
        if self.psi_path is not None:
            out += ['psi_path=%s' % repr(self.psi_path)]
        if self.psi_state is not None:
            out += ['psi_state=%s' % const.probe_sb_lifecycle1.get(self.psi_state, self.psi_state)]
        if self.psi_storage_type is not None:
            out += ['psi_storage_type=%s' % const.probe_storage_type1.get(self.psi_storage_type, self.psi_storage_type)]
        if self.psi_flavors is not None:
            out += ['psi_flavors=%s' % ','.join([const.probe_auth_flavor1.get(x, x) for x in self.psi_flavors])]
        if self.psi_bytes_max is not None:
            out += ['psi_bytes_max=%s' % repr(self.psi_bytes_max)]
        if self.psi_bytes_used is not None:
            out += ['psi_bytes_used=%s' % repr(self.psi_bytes_used)]
        if self.psi_inodes_max is not None:
            out += ['psi_inodes_max=%s' % repr(self.psi_inodes_max)]
        if self.psi_inodes_used is not None:
            out += ['psi_inodes_used=%s' % repr(self.psi_inodes_used)]
        return 'probe_sb_info1(%s)' % ', '.join(out)
    __str__ = __repr__

class SB_LIST1resok:
    # XDR definition:
    # struct SB_LIST1resok {
    #     probe_sb_info1 slr_sbs<>;
    # };
    def __init__(self, slr_sbs=None):
        self.slr_sbs = slr_sbs

    def __repr__(self):
        out = []
        if self.slr_sbs is not None:
            out += ['slr_sbs=%s' % repr(self.slr_sbs)]
        return 'SB_LIST1resok(%s)' % ', '.join(out)
    __str__ = __repr__

class SB_LIST1res:
    # XDR definition:
    # union SB_LIST1res switch(probe_stat1 slr_status) {
    #     case PROBE1_OK:
    #         SB_LIST1resok slr_resok;
    #     default:
    #         void;
    # };
    def __init__(self, slr_status=None, slr_resok=None):
        self.slr_status = slr_status
        self.slr_resok = slr_resok

    switch = property(lambda s: {const.PROBE1_OK:s.slr_resok,}.get(s.slr_status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.slr_status is not None:
            out += ['slr_status=%s' % const.probe_stat1.get(self.slr_status, self.slr_status)]
        if self.slr_resok is not None:
            out += ['slr_resok=%s' % repr(self.slr_resok)]
        return 'SB_LIST1res(%s)' % ', '.join(out)
    __str__ = __repr__

class SB_CREATE1args:
    # XDR definition:
    # struct SB_CREATE1args {
    #     string sca_path<>;
    #     probe_storage_type1 sca_storage_type;
    # };
    def __init__(self, sca_path=None, sca_storage_type=None):
        self.sca_path = sca_path
        self.sca_storage_type = sca_storage_type

    def __repr__(self):
        out = []
        if self.sca_path is not None:
            out += ['sca_path=%s' % repr(self.sca_path)]
        if self.sca_storage_type is not None:
            out += ['sca_storage_type=%s' % const.probe_storage_type1.get(self.sca_storage_type, self.sca_storage_type)]
        return 'SB_CREATE1args(%s)' % ', '.join(out)
    __str__ = __repr__

class SB_CREATE1res:
    # XDR definition:
    # union SB_CREATE1res switch(probe_stat1 scr_status) {
    #     case PROBE1_OK:
    #         probe_sb_info1 scr_resok;
    #     default:
    #         void;
    # };
    def __init__(self, scr_status=None, scr_resok=None):
        self.scr_status = scr_status
        self.scr_resok = scr_resok

    switch = property(lambda s: {const.PROBE1_OK:s.scr_resok,}.get(s.scr_status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.scr_status is not None:
            out += ['scr_status=%s' % const.probe_stat1.get(self.scr_status, self.scr_status)]
        if self.scr_resok is not None:
            out += ['scr_resok=%s' % repr(self.scr_resok)]
        return 'SB_CREATE1res(%s)' % ', '.join(out)
    __str__ = __repr__

class SB_MOUNT1args:
    # XDR definition:
    # struct SB_MOUNT1args {
    #     uhyper sma_id;
    #     string sma_path<>;
    # };
    def __init__(self, sma_id=None, sma_path=None):
        self.sma_id = sma_id
        self.sma_path = sma_path

    def __repr__(self):
        out = []
        if self.sma_id is not None:
            out += ['sma_id=%s' % repr(self.sma_id)]
        if self.sma_path is not None:
            out += ['sma_path=%s' % repr(self.sma_path)]
        return 'SB_MOUNT1args(%s)' % ', '.join(out)
    __str__ = __repr__

class SB_UNMOUNT1args:
    # XDR definition:
    # struct SB_UNMOUNT1args {
    #     uhyper sua_id;
    # };
    def __init__(self, sua_id=None):
        self.sua_id = sua_id

    def __repr__(self):
        out = []
        if self.sua_id is not None:
            out += ['sua_id=%s' % repr(self.sua_id)]
        return 'SB_UNMOUNT1args(%s)' % ', '.join(out)
    __str__ = __repr__

class SB_DESTROY1args:
    # XDR definition:
    # struct SB_DESTROY1args {
    #     uhyper sda_id;
    # };
    def __init__(self, sda_id=None):
        self.sda_id = sda_id

    def __repr__(self):
        out = []
        if self.sda_id is not None:
            out += ['sda_id=%s' % repr(self.sda_id)]
        return 'SB_DESTROY1args(%s)' % ', '.join(out)
    __str__ = __repr__

class SB_GET1args:
    # XDR definition:
    # struct SB_GET1args {
    #     uhyper sga_id;
    # };
    def __init__(self, sga_id=None):
        self.sga_id = sga_id

    def __repr__(self):
        out = []
        if self.sga_id is not None:
            out += ['sga_id=%s' % repr(self.sga_id)]
        return 'SB_GET1args(%s)' % ', '.join(out)
    __str__ = __repr__

class SB_GET1res:
    # XDR definition:
    # union SB_GET1res switch(probe_stat1 sgr_status) {
    #     case PROBE1_OK:
    #         probe_sb_info1 sgr_resok;
    #     default:
    #         void;
    # };
    def __init__(self, sgr_status=None, sgr_resok=None):
        self.sgr_status = sgr_status
        self.sgr_resok = sgr_resok

    switch = property(lambda s: {const.PROBE1_OK:s.sgr_resok,}.get(s.sgr_status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.sgr_status is not None:
            out += ['sgr_status=%s' % const.probe_stat1.get(self.sgr_status, self.sgr_status)]
        if self.sgr_resok is not None:
            out += ['sgr_resok=%s' % repr(self.sgr_resok)]
        return 'SB_GET1res(%s)' % ', '.join(out)
    __str__ = __repr__

class SB_SET_FLAVORS1args:
    # XDR definition:
    # struct SB_SET_FLAVORS1args {
    #     uhyper sfa_id;
    #     probe_auth_flavor1 sfa_flavors<PROBE1_MAX_FLAVORS>;
    # };
    def __init__(self, sfa_id=None, sfa_flavors=None):
        self.sfa_id = sfa_id
        self.sfa_flavors = sfa_flavors

    def __repr__(self):
        out = []
        if self.sfa_id is not None:
            out += ['sfa_id=%s' % repr(self.sfa_id)]
        if self.sfa_flavors is not None:
            out += ['sfa_flavors=%s' % ','.join([const.probe_auth_flavor1.get(x, x) for x in self.sfa_flavors])]
        return 'SB_SET_FLAVORS1args(%s)' % ', '.join(out)
    __str__ = __repr__

class SB_LINT_FLAVORS1resok:
    # XDR definition:
    # struct SB_LINT_FLAVORS1resok {
    #     uint lfr_warnings;
    #     string lfr_messages<>;
    # };
    def __init__(self, lfr_warnings=None, lfr_messages=None):
        self.lfr_warnings = lfr_warnings
        self.lfr_messages = lfr_messages

    def __repr__(self):
        out = []
        if self.lfr_warnings is not None:
            out += ['lfr_warnings=%s' % repr(self.lfr_warnings)]
        if self.lfr_messages is not None:
            out += ['lfr_messages=%s' % repr(self.lfr_messages)]
        return 'SB_LINT_FLAVORS1resok(%s)' % ', '.join(out)
    __str__ = __repr__

class SB_LINT_FLAVORS1res:
    # XDR definition:
    # union SB_LINT_FLAVORS1res switch(probe_stat1 lfr_status) {
    #     case PROBE1_OK:
    #         SB_LINT_FLAVORS1resok lfr_resok;
    #     default:
    #         void;
    # };
    def __init__(self, lfr_status=None, lfr_resok=None):
        self.lfr_status = lfr_status
        self.lfr_resok = lfr_resok

    switch = property(lambda s: {const.PROBE1_OK:s.lfr_resok,}.get(s.lfr_status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.lfr_status is not None:
            out += ['lfr_status=%s' % const.probe_stat1.get(self.lfr_status, self.lfr_status)]
        if self.lfr_resok is not None:
            out += ['lfr_resok=%s' % repr(self.lfr_resok)]
        return 'SB_LINT_FLAVORS1res(%s)' % ', '.join(out)
    __str__ = __repr__

class probe_sb_fs_usage1:
    # XDR definition:
    # struct probe_sb_fs_usage1 {
    #     uhyper sfu_sb_id;
    #     string sfu_sb_path<>;
    #     uhyper sfu_total_bytes;
    #     uhyper sfu_free_bytes;
    #     uhyper sfu_used_bytes;
    #     uhyper sfu_total_files;
    #     uhyper sfu_free_files;
    #     uhyper sfu_used_files;
    # };
    def __init__(self, sfu_sb_id=None, sfu_sb_path=None, sfu_total_bytes=None, sfu_free_bytes=None, sfu_used_bytes=None, sfu_total_files=None, sfu_free_files=None, sfu_used_files=None):
        self.sfu_sb_id = sfu_sb_id
        self.sfu_sb_path = sfu_sb_path
        self.sfu_total_bytes = sfu_total_bytes
        self.sfu_free_bytes = sfu_free_bytes
        self.sfu_used_bytes = sfu_used_bytes
        self.sfu_total_files = sfu_total_files
        self.sfu_free_files = sfu_free_files
        self.sfu_used_files = sfu_used_files

    def __repr__(self):
        out = []
        if self.sfu_sb_id is not None:
            out += ['sfu_sb_id=%s' % repr(self.sfu_sb_id)]
        if self.sfu_sb_path is not None:
            out += ['sfu_sb_path=%s' % repr(self.sfu_sb_path)]
        if self.sfu_total_bytes is not None:
            out += ['sfu_total_bytes=%s' % repr(self.sfu_total_bytes)]
        if self.sfu_free_bytes is not None:
            out += ['sfu_free_bytes=%s' % repr(self.sfu_free_bytes)]
        if self.sfu_used_bytes is not None:
            out += ['sfu_used_bytes=%s' % repr(self.sfu_used_bytes)]
        if self.sfu_total_files is not None:
            out += ['sfu_total_files=%s' % repr(self.sfu_total_files)]
        if self.sfu_free_files is not None:
            out += ['sfu_free_files=%s' % repr(self.sfu_free_files)]
        if self.sfu_used_files is not None:
            out += ['sfu_used_files=%s' % repr(self.sfu_used_files)]
        return 'probe_sb_fs_usage1(%s)' % ', '.join(out)
    __str__ = __repr__

class FS_USAGE1resok:
    # XDR definition:
    # struct FS_USAGE1resok {
    #     uhyper fur_total_bytes;
    #     uhyper fur_free_bytes;
    #     uhyper fur_used_bytes;
    #     uhyper fur_total_files;
    #     uhyper fur_free_files;
    #     uhyper fur_used_files;
    #     probe_sb_fs_usage1 fur_per_sb<>;
    # };
    def __init__(self, fur_total_bytes=None, fur_free_bytes=None, fur_used_bytes=None, fur_total_files=None, fur_free_files=None, fur_used_files=None, fur_per_sb=None):
        self.fur_total_bytes = fur_total_bytes
        self.fur_free_bytes = fur_free_bytes
        self.fur_used_bytes = fur_used_bytes
        self.fur_total_files = fur_total_files
        self.fur_free_files = fur_free_files
        self.fur_used_files = fur_used_files
        self.fur_per_sb = fur_per_sb

    def __repr__(self):
        out = []
        if self.fur_total_bytes is not None:
            out += ['fur_total_bytes=%s' % repr(self.fur_total_bytes)]
        if self.fur_free_bytes is not None:
            out += ['fur_free_bytes=%s' % repr(self.fur_free_bytes)]
        if self.fur_used_bytes is not None:
            out += ['fur_used_bytes=%s' % repr(self.fur_used_bytes)]
        if self.fur_total_files is not None:
            out += ['fur_total_files=%s' % repr(self.fur_total_files)]
        if self.fur_free_files is not None:
            out += ['fur_free_files=%s' % repr(self.fur_free_files)]
        if self.fur_used_files is not None:
            out += ['fur_used_files=%s' % repr(self.fur_used_files)]
        if self.fur_per_sb is not None:
            out += ['fur_per_sb=%s' % repr(self.fur_per_sb)]
        return 'FS_USAGE1resok(%s)' % ', '.join(out)
    __str__ = __repr__

class FS_USAGE1res:
    # XDR definition:
    # union FS_USAGE1res switch(probe_stat1 fur_status) {
    #     case PROBE1_OK:
    #         FS_USAGE1resok fur_resok;
    #     default:
    #         void;
    # };
    def __init__(self, fur_status=None, fur_resok=None):
        self.fur_status = fur_status
        self.fur_resok = fur_resok

    switch = property(lambda s: {const.PROBE1_OK:s.fur_resok,}.get(s.fur_status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.fur_status is not None:
            out += ['fur_status=%s' % const.probe_stat1.get(self.fur_status, self.fur_status)]
        if self.fur_resok is not None:
            out += ['fur_resok=%s' % repr(self.fur_resok)]
        return 'FS_USAGE1res(%s)' % ', '.join(out)
    __str__ = __repr__

class probe_nfs4_op1:
    # XDR definition:
    # struct probe_nfs4_op1 {
    #     uint pno_op;
    #     string pno_name<>;
    #     uhyper pno_calls;
    #     uhyper pno_errors;
    #     uhyper pno_bytes_in;
    #     uhyper pno_bytes_out;
    #     uhyper pno_duration_total;
    #     uhyper pno_duration_max;
    # };
    def __init__(self, pno_op=None, pno_name=None, pno_calls=None, pno_errors=None, pno_bytes_in=None, pno_bytes_out=None, pno_duration_total=None, pno_duration_max=None):
        self.pno_op = pno_op
        self.pno_name = pno_name
        self.pno_calls = pno_calls
        self.pno_errors = pno_errors
        self.pno_bytes_in = pno_bytes_in
        self.pno_bytes_out = pno_bytes_out
        self.pno_duration_total = pno_duration_total
        self.pno_duration_max = pno_duration_max

    def __repr__(self):
        out = []
        if self.pno_op is not None:
            out += ['pno_op=%s' % repr(self.pno_op)]
        if self.pno_name is not None:
            out += ['pno_name=%s' % repr(self.pno_name)]
        if self.pno_calls is not None:
            out += ['pno_calls=%s' % repr(self.pno_calls)]
        if self.pno_errors is not None:
            out += ['pno_errors=%s' % repr(self.pno_errors)]
        if self.pno_bytes_in is not None:
            out += ['pno_bytes_in=%s' % repr(self.pno_bytes_in)]
        if self.pno_bytes_out is not None:
            out += ['pno_bytes_out=%s' % repr(self.pno_bytes_out)]
        if self.pno_duration_total is not None:
            out += ['pno_duration_total=%s' % repr(self.pno_duration_total)]
        if self.pno_duration_max is not None:
            out += ['pno_duration_max=%s' % repr(self.pno_duration_max)]
        return 'probe_nfs4_op1(%s)' % ', '.join(out)
    __str__ = __repr__

class probe_sb_nfs4_op_stats1:
    # XDR definition:
    # struct probe_sb_nfs4_op_stats1 {
    #     uhyper sns_sb_id;
    #     string sns_sb_path<>;
    #     probe_nfs4_op1 sns_ops<>;
    # };
    def __init__(self, sns_sb_id=None, sns_sb_path=None, sns_ops=None):
        self.sns_sb_id = sns_sb_id
        self.sns_sb_path = sns_sb_path
        self.sns_ops = sns_ops

    def __repr__(self):
        out = []
        if self.sns_sb_id is not None:
            out += ['sns_sb_id=%s' % repr(self.sns_sb_id)]
        if self.sns_sb_path is not None:
            out += ['sns_sb_path=%s' % repr(self.sns_sb_path)]
        if self.sns_ops is not None:
            out += ['sns_ops=%s' % repr(self.sns_ops)]
        return 'probe_sb_nfs4_op_stats1(%s)' % ', '.join(out)
    __str__ = __repr__

class NFS4_OP_STATS1resok:
    # XDR definition:
    # struct NFS4_OP_STATS1resok {
    #     probe_nfs4_op1 nosr_ops<>;
    #     probe_sb_nfs4_op_stats1 nosr_per_sb<>;
    # };
    def __init__(self, nosr_ops=None, nosr_per_sb=None):
        self.nosr_ops = nosr_ops
        self.nosr_per_sb = nosr_per_sb

    def __repr__(self):
        out = []
        if self.nosr_ops is not None:
            out += ['nosr_ops=%s' % repr(self.nosr_ops)]
        if self.nosr_per_sb is not None:
            out += ['nosr_per_sb=%s' % repr(self.nosr_per_sb)]
        return 'NFS4_OP_STATS1resok(%s)' % ', '.join(out)
    __str__ = __repr__

class NFS4_OP_STATS1res:
    # XDR definition:
    # union NFS4_OP_STATS1res switch(probe_stat1 nosr_status) {
    #     case PROBE1_OK:
    #         NFS4_OP_STATS1resok nosr_resok;
    #     default:
    #         void;
    # };
    def __init__(self, nosr_status=None, nosr_resok=None):
        self.nosr_status = nosr_status
        self.nosr_resok = nosr_resok

    switch = property(lambda s: {const.PROBE1_OK:s.nosr_resok,}.get(s.nosr_status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.nosr_status is not None:
            out += ['nosr_status=%s' % const.probe_stat1.get(self.nosr_status, self.nosr_status)]
        if self.nosr_resok is not None:
            out += ['nosr_resok=%s' % repr(self.nosr_resok)]
        return 'NFS4_OP_STATS1res(%s)' % ', '.join(out)
    __str__ = __repr__

class probe_layout_error1:
    # XDR definition:
    # struct probe_layout_error1 {
    #     uint ple_id;
    #     string ple_name<>;
    #     uhyper ple_total;
    #     uhyper ple_access;
    #     uhyper ple_io;
    #     uhyper ple_other;
    # };
    def __init__(self, ple_id=None, ple_name=None, ple_total=None, ple_access=None, ple_io=None, ple_other=None):
        self.ple_id = ple_id
        self.ple_name = ple_name
        self.ple_total = ple_total
        self.ple_access = ple_access
        self.ple_io = ple_io
        self.ple_other = ple_other

    def __repr__(self):
        out = []
        if self.ple_id is not None:
            out += ['ple_id=%s' % repr(self.ple_id)]
        if self.ple_name is not None:
            out += ['ple_name=%s' % repr(self.ple_name)]
        if self.ple_total is not None:
            out += ['ple_total=%s' % repr(self.ple_total)]
        if self.ple_access is not None:
            out += ['ple_access=%s' % repr(self.ple_access)]
        if self.ple_io is not None:
            out += ['ple_io=%s' % repr(self.ple_io)]
        if self.ple_other is not None:
            out += ['ple_other=%s' % repr(self.ple_other)]
        return 'probe_layout_error1(%s)' % ', '.join(out)
    __str__ = __repr__

class LAYOUT_ERRORS1resok:
    # XDR definition:
    # struct LAYOUT_ERRORS1resok {
    #     probe_layout_error1 ler_global;
    #     probe_layout_error1 ler_dstores<>;
    #     probe_layout_error1 ler_clients<>;
    #     probe_layout_error1 ler_sbs<>;
    # };
    def __init__(self, ler_global=None, ler_dstores=None, ler_clients=None, ler_sbs=None):
        self.ler_global = ler_global
        self.ler_dstores = ler_dstores
        self.ler_clients = ler_clients
        self.ler_sbs = ler_sbs

    def __getattr__(self, attr):
        return getattr(self.ler_global, attr)

    def __repr__(self):
        out = []
        if self.ler_global is not None:
            out += ['ler_global=%s' % repr(self.ler_global)]
        if self.ler_dstores is not None:
            out += ['ler_dstores=%s' % repr(self.ler_dstores)]
        if self.ler_clients is not None:
            out += ['ler_clients=%s' % repr(self.ler_clients)]
        if self.ler_sbs is not None:
            out += ['ler_sbs=%s' % repr(self.ler_sbs)]
        return 'LAYOUT_ERRORS1resok(%s)' % ', '.join(out)
    __str__ = __repr__

class LAYOUT_ERRORS1res:
    # XDR definition:
    # union LAYOUT_ERRORS1res switch(probe_stat1 ler_status) {
    #     case PROBE1_OK:
    #         LAYOUT_ERRORS1resok ler_resok;
    #     default:
    #         void;
    # };
    def __init__(self, ler_status=None, ler_resok=None):
        self.ler_status = ler_status
        self.ler_resok = ler_resok

    switch = property(lambda s: {const.PROBE1_OK:s.ler_resok,}.get(s.ler_status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.ler_status is not None:
            out += ['ler_status=%s' % const.probe_stat1.get(self.ler_status, self.ler_status)]
        if self.ler_resok is not None:
            out += ['ler_resok=%s' % repr(self.ler_resok)]
        return 'LAYOUT_ERRORS1res(%s)' % ', '.join(out)
    __str__ = __repr__

