# DO NOT EDIT - generated by xdr_parser.py from probe1_xdr.x
# Apply changes to probe1_xdr.x instead.
import sys,os
from . import probe1_xdr_const as const
from . import probe1_xdr_type as types

try:
    import xdrlib3 as xdrlib
    from xdrlib3 import Error as XDRError
except:
    import xdrlib as xdrlib
    from xdrlib import Error as XDRError

class nullclass(object):
    pass

class PROBE1_XDRPacker(xdrlib.Packer):
    def __init__(self, check_enum=True, check_array=True):
        xdrlib.Packer.__init__(self)
        self.check_enum = check_enum
        self.check_array = check_array

    pack_int = xdrlib.Packer.pack_int
    pack_uint = xdrlib.Packer.pack_uint
    pack_unsigned = xdrlib.Packer.pack_uint
    pack_hyper = xdrlib.Packer.pack_hyper
    pack_uhyper = xdrlib.Packer.pack_uhyper
    pack_float = xdrlib.Packer.pack_float
    pack_double = xdrlib.Packer.pack_double
    pack_quadruple = xdrlib.Packer.pack_double
    pack_bool = xdrlib.Packer.pack_bool
    pack_opaque = xdrlib.Packer.pack_opaque
    pack_string = xdrlib.Packer.pack_string

    def pack_probe1_address_string(self, data):
        if hasattr(self, 'filter_probe1_address_string'):
            data = getattr(self, 'filter_probe1_address_string')(data)
        self.pack_fopaque(const.PROBE1_ADDR_LEN, data)

    def pack_probe_time1(self, data):
        if hasattr(self, 'filter_probe_time1'):
            data = getattr(self, 'filter_probe_time1')(data)
        if data.seconds is None:
            raise TypeError('data.seconds == None')
        self.pack_uint(data.seconds)
        if data.nseconds is None:
            raise TypeError('data.nseconds == None')
        self.pack_uint(data.nseconds)

    def pack_probe_stat1(self, data):
        if hasattr(self, 'filter_probe_stat1'):
            data = getattr(self, 'filter_probe_stat1')(data)
        if self.check_enum and data not in [const.PROBE1_OK, const.PROBE1ERR_PERM, const.PROBE1ERR_NOENT, const.PROBE1ERR_IO, const.PROBE1ERR_ENXIO, const.PROBE1ERR_BADF, const.PROBE1ERR_AGAIN, const.PROBE1ERR_NOMEM, const.PROBE1ERR_ACCES, const.PROBE1ERR_BUSY, const.PROBE1ERR_EXIST, const.PROBE1ERR_NOTDIR, const.PROBE1ERR_INVAL, const.PROBE1ERR_NOSPC, const.PROBE1ERR_STALE, const.PROBE1ERR_ALREADY, const.PROBE1ERR_NOTSUPP, const.PROBE1ERR_SERVERFAULT, const.PROBE1ERR_DELAY, const.PROBE1ERR_BADXDR, const.PROBE1ERR_BADNAME]:
            raise XDRError('value=%s not in enum probe_stat1' % data)
        self.pack_int(data)

    def pack_probe_op1(self, data):
        if hasattr(self, 'filter_probe_op1'):
            data = getattr(self, 'filter_probe_op1')(data)
        if data.po_op is None:
            raise TypeError('data.po_op == None')
        self.pack_uint(data.po_op)
        if data.po_name is None:
            raise TypeError('data.po_name == None')
        self.pack_string(data.po_name)
        if data.po_calls is None:
            raise TypeError('data.po_calls == None')
        self.pack_uhyper(data.po_calls)
        if data.po_errors is None:
            raise TypeError('data.po_errors == None')
        self.pack_uhyper(data.po_errors)
        if data.po_max_duration is None:
            raise TypeError('data.po_max_duration == None')
        self.pack_uhyper(data.po_max_duration)
        if data.po_total_duration is None:
            raise TypeError('data.po_total_duration == None')
        self.pack_uhyper(data.po_total_duration)
        if data.po_bucket_1ms is None:
            raise TypeError('data.po_bucket_1ms == None')
        self.pack_uhyper(data.po_bucket_1ms)
        if data.po_bucket_10ms is None:
            raise TypeError('data.po_bucket_10ms == None')
        self.pack_uhyper(data.po_bucket_10ms)
        if data.po_bucket_100ms is None:
            raise TypeError('data.po_bucket_100ms == None')
        self.pack_uhyper(data.po_bucket_100ms)
        if data.po_bucket_1s is None:
            raise TypeError('data.po_bucket_1s == None')
        self.pack_uhyper(data.po_bucket_1s)
        if data.po_bucket_10s is None:
            raise TypeError('data.po_bucket_10s == None')
        self.pack_uhyper(data.po_bucket_10s)
        if data.po_bucket_rest is None:
            raise TypeError('data.po_bucket_rest == None')
        self.pack_uhyper(data.po_bucket_rest)
        if data.po_median_ns is None:
            raise TypeError('data.po_median_ns == None')
        self.pack_uhyper(data.po_median_ns)
        if data.po_p90_ns is None:
            raise TypeError('data.po_p90_ns == None')
        self.pack_uhyper(data.po_p90_ns)
        if data.po_p99_ns is None:
            raise TypeError('data.po_p99_ns == None')
        self.pack_uhyper(data.po_p99_ns)
        if data.po_p999_ns is None:
            raise TypeError('data.po_p999_ns == None')
        self.pack_uhyper(data.po_p999_ns)
        if data.po_min_ns is None:
            raise TypeError('data.po_min_ns == None')
        self.pack_uhyper(data.po_min_ns)
        if data.po_max_ns is None:
            raise TypeError('data.po_max_ns == None')
        self.pack_uhyper(data.po_max_ns)
        if data.po_mean_ns is None:
            raise TypeError('data.po_mean_ns == None')
        self.pack_uhyper(data.po_mean_ns)

    def pack_probe_program1(self, data):
        if hasattr(self, 'filter_probe_program1'):
            data = getattr(self, 'filter_probe_program1')(data)
        if data.pp_program is None:
            raise TypeError('data.pp_program == None')
        self.pack_uint(data.pp_program)
        if data.pp_version is None:
            raise TypeError('data.pp_version == None')
        self.pack_uint(data.pp_version)
        if data.pp_count is None:
            raise TypeError('data.pp_count == None')
        self.pack_uhyper(data.pp_count)
        if data.pp_replied_errors is None:
            raise TypeError('data.pp_replied_errors == None')
        self.pack_uhyper(data.pp_replied_errors)
        if data.pp_rejected_errors is None:
            raise TypeError('data.pp_rejected_errors == None')
        self.pack_uhyper(data.pp_rejected_errors)
        if data.pp_accepted_errors is None:
            raise TypeError('data.pp_accepted_errors == None')
        self.pack_uhyper(data.pp_accepted_errors)
        if data.pp_authed_errors is None:
            raise TypeError('data.pp_authed_errors == None')
        self.pack_uhyper(data.pp_authed_errors)
        if data.pp_ops is None:
            raise TypeError('data.pp_ops == None')
        self.pack_array(data.pp_ops, self.pack_probe_op1)

    def pack_STATS_GATHER1args(self, data):
        if hasattr(self, 'filter_STATS_GATHER1args'):
            data = getattr(self, 'filter_STATS_GATHER1args')(data)
        if data.psga_program is None:
            raise TypeError('data.psga_program == None')
        self.pack_uint(data.psga_program)
        if data.psga_version is None:
            raise TypeError('data.psga_version == None')
        self.pack_uint(data.psga_version)

    def pack_STATS_GATHER1resok(self, data):
        if hasattr(self, 'filter_STATS_GATHER1resok'):
            data = getattr(self, 'filter_STATS_GATHER1resok')(data)
        if data.psgr_program is None:
            raise TypeError('data.psgr_program == None')
        self.pack_probe_program1(data.psgr_program)

    def pack_STATS_GATHER1res(self, data):
        if hasattr(self, 'filter_STATS_GATHER1res'):
            data = getattr(self, 'filter_STATS_GATHER1res')(data)
        if data.psgr_status is None:
            raise TypeError('data.psgr_status == None')
        self.pack_probe_stat1(data.psgr_status)
        if data.psgr_status == const.PROBE1_OK:
            if data.psgr_resok is None:
                raise TypeError('data.psgr_resok == None')
            self.pack_STATS_GATHER1resok(data.psgr_resok)
        else:
            pass

    def pack_CONTEXT1resok(self, data):
        if hasattr(self, 'filter_CONTEXT1resok'):
            data = getattr(self, 'filter_CONTEXT1resok')(data)
        if data.pcr_created is None:
            raise TypeError('data.pcr_created == None')
        self.pack_uhyper(data.pcr_created)
        if data.pcr_freed is None:
            raise TypeError('data.pcr_freed == None')
        self.pack_uhyper(data.pcr_freed)
        if data.pcr_active_cancelled is None:
            raise TypeError('data.pcr_active_cancelled == None')
        self.pack_uhyper(data.pcr_active_cancelled)
        if data.pcr_active_destroyed is None:
            raise TypeError('data.pcr_active_destroyed == None')
        self.pack_uhyper(data.pcr_active_destroyed)
        if data.pcr_cancelled_freed is None:
            raise TypeError('data.pcr_cancelled_freed == None')
        self.pack_uhyper(data.pcr_cancelled_freed)
        if data.pcr_destroyed_freed is None:
            raise TypeError('data.pcr_destroyed_freed == None')
        self.pack_uhyper(data.pcr_destroyed_freed)

    def pack_CONTEXT1res(self, data):
        if hasattr(self, 'filter_CONTEXT1res'):
            data = getattr(self, 'filter_CONTEXT1res')(data)
        if data.pcr_status is None:
            raise TypeError('data.pcr_status == None')
        self.pack_probe_stat1(data.pcr_status)
        if data.pcr_status == const.PROBE1_OK:
            if data.pcr_resok is None:
                raise TypeError('data.pcr_resok == None')
            self.pack_CONTEXT1resok(data.pcr_resok)
        else:
            pass

    pack_probe_dump1 = pack_uint

    def pack_probe_trace_category1(self, data):
        if hasattr(self, 'filter_probe_trace_category1'):
            data = getattr(self, 'filter_probe_trace_category1')(data)
        if self.check_enum and data not in [const.PROBE1_TRACE_CAT_GENERAL, const.PROBE1_TRACE_CAT_IO, const.PROBE1_TRACE_CAT_RPC, const.PROBE1_TRACE_CAT_NFS, const.PROBE1_TRACE_CAT_NLM, const.PROBE1_TRACE_CAT_FS, const.PROBE1_TRACE_CAT_LOG, const.PROBE1_TRACE_CAT_SECURITY, const.PROBE1_TRACE_CAT_LIFECYCLE, const.PROBE1_TRACE_CAT_ALL]:
            raise XDRError('value=%s not in enum probe_trace_category1' % data)
        self.pack_int(data)

    def pack_TRACE_SET1args(self, data):
        if hasattr(self, 'filter_TRACE_SET1args'):
            data = getattr(self, 'filter_TRACE_SET1args')(data)
        if data.tsa_cat is None:
            raise TypeError('data.tsa_cat == None')
        self.pack_probe_trace_category1(data.tsa_cat)
        if data.tsa_set is None:
            raise TypeError('data.tsa_set == None')
        self.pack_uint(data.tsa_set)

    def pack_TRACES_LIST1args(self, data):
        if hasattr(self, 'filter_TRACES_LIST1args'):
            data = getattr(self, 'filter_TRACES_LIST1args')(data)
        if data.tla_cat is None:
            raise TypeError('data.tla_cat == None')
        self.pack_probe_trace_category1(data.tla_cat)

    def pack_probe_trace_list1(self, data):
        if hasattr(self, 'filter_probe_trace_list1'):
            data = getattr(self, 'filter_probe_trace_list1')(data)
        if data.ptl_cat is None:
            raise TypeError('data.ptl_cat == None')
        self.pack_probe_trace_category1(data.ptl_cat)
        if data.ptl_set is None:
            raise TypeError('data.ptl_set == None')
        self.pack_uint(data.ptl_set)

    def pack_TRACES_LIST1resok(self, data):
        if hasattr(self, 'filter_TRACES_LIST1resok'):
            data = getattr(self, 'filter_TRACES_LIST1resok')(data)
        if data.tlr_list is None:
            raise TypeError('data.tlr_list == None')
        self.pack_array(data.tlr_list, self.pack_probe_trace_list1)

    def pack_TRACES_LIST1res(self, data):
        if hasattr(self, 'filter_TRACES_LIST1res'):
            data = getattr(self, 'filter_TRACES_LIST1res')(data)
        if data.tlr_status is None:
            raise TypeError('data.tlr_status == None')
        self.pack_probe_stat1(data.tlr_status)
        if data.tlr_status == const.PROBE1_OK:
            if data.tlr_resok is None:
                raise TypeError('data.tlr_resok == None')
            self.pack_TRACES_LIST1resok(data.tlr_resok)
        else:
            pass

    def pack_HEARTBEAT1args(self, data):
        if hasattr(self, 'filter_HEARTBEAT1args'):
            data = getattr(self, 'filter_HEARTBEAT1args')(data)
        if data.hba_period is None:
            raise TypeError('data.hba_period == None')
        self.pack_uint(data.hba_period)
        if data.hba_period_set is None:
            raise TypeError('data.hba_period_set == None')
        self.pack_uint(data.hba_period_set)

    def pack_HEARTBEAT1resok(self, data):
        if hasattr(self, 'filter_HEARTBEAT1resok'):
            data = getattr(self, 'filter_HEARTBEAT1resok')(data)
        if data.hbr_period is None:
            raise TypeError('data.hbr_period == None')
        self.pack_uint(data.hbr_period)

    def pack_HEARTBEAT1res(self, data):
        if hasattr(self, 'filter_HEARTBEAT1res'):
            data = getattr(self, 'filter_HEARTBEAT1res')(data)
        if data.hbr_status is None:
            raise TypeError('data.hbr_status == None')
        self.pack_probe_stat1(data.hbr_status)
        if data.hbr_status == const.PROBE1_OK:
            if data.hbr_resok is None:
                raise TypeError('data.hbr_resok == None')
            self.pack_HEARTBEAT1resok(data.hbr_resok)
        else:
            pass

    def pack_probe_op_type1(self, data):
        if hasattr(self, 'filter_probe_op_type1'):
            data = getattr(self, 'filter_probe_op_type1')(data)
        if self.check_enum and data not in [const.PROBE1_OP_TYPE_ACCEPT, const.PROBE1_OP_TYPE_READ, const.PROBE1_OP_TYPE_WRITE, const.PROBE1_OP_TYPE_CONNECT, const.PROBE1_OP_TYPE_RPC_REQ, const.PROBE1_OP_TYPE_HEARTBEAT, const.PROBE1_OP_TYPE_ALL]:
            raise XDRError('value=%s not in enum probe_op_type1' % data)
        self.pack_int(data)

    def pack_probe_io_context1(self, data):
        if hasattr(self, 'filter_probe_io_context1'):
            data = getattr(self, 'filter_probe_io_context1')(data)
        if data.pic_op_type is None:
            raise TypeError('data.pic_op_type == None')
        self.pack_probe_op_type1(data.pic_op_type)
        if data.pic_fd is None:
            raise TypeError('data.pic_fd == None')
        self.pack_int(data.pic_fd)
        if data.pic_id is None:
            raise TypeError('data.pic_id == None')
        self.pack_uint(data.pic_id)
        if data.pic_xid is None:
            raise TypeError('data.pic_xid == None')
        self.pack_uint(data.pic_xid)
        if data.pic_buffer_len is None:
            raise TypeError('data.pic_buffer_len == None')
        self.pack_uhyper(data.pic_buffer_len)
        if data.pic_position is None:
            raise TypeError('data.pic_position == None')
        self.pack_uhyper(data.pic_position)
        if data.pic_expected_len is None:
            raise TypeError('data.pic_expected_len == None')
        self.pack_uhyper(data.pic_expected_len)
        if data.pic_state is None:
            raise TypeError('data.pic_state == None')
        self.pack_uhyper(data.pic_state)
        if data.pic_count is None:
            raise TypeError('data.pic_count == None')
        self.pack_uhyper(data.pic_count)
        if data.pic_action_time is None:
            raise TypeError('data.pic_action_time == None')
        self.pack_probe_time1(data.pic_action_time)

    def pack_probe_fd1(self, data):
        if hasattr(self, 'filter_probe_fd1'):
            data = getattr(self, 'filter_probe_fd1')(data)
        if data.pf_fd is None:
            raise TypeError('data.pf_fd == None')
        self.pack_int(data.pf_fd)
        if data.pf_server_port is None:
            raise TypeError('data.pf_server_port == None')
        self.pack_uint(data.pf_server_port)
        if data.pf_client is None:
            raise TypeError('data.pf_client == None')
        self.pack_probe1_address_string(data.pf_client)

    def pack_IO_CONTEXTS_LIST1args(self, data):
        if hasattr(self, 'filter_IO_CONTEXTS_LIST1args'):
            data = getattr(self, 'filter_IO_CONTEXTS_LIST1args')(data)
        if data.icla_fd is None:
            raise TypeError('data.icla_fd == None')
        self.pack_int(data.icla_fd)
        if data.icla_op is None:
            raise TypeError('data.icla_op == None')
        self.pack_probe_op_type1(data.icla_op)
        if data.icla_state is None:
            raise TypeError('data.icla_state == None')
        self.pack_uhyper(data.icla_state)

    def pack_IO_CONTEXTS_LIST1resok(self, data):
        if hasattr(self, 'filter_IO_CONTEXTS_LIST1resok'):
            data = getattr(self, 'filter_IO_CONTEXTS_LIST1resok')(data)
        if data.iclr_pic is None:
            raise TypeError('data.iclr_pic == None')
        self.pack_array(data.iclr_pic, self.pack_probe_io_context1)
        if data.iclr_now is None:
            raise TypeError('data.iclr_now == None')
        self.pack_probe_time1(data.iclr_now)

    def pack_IO_CONTEXTS_LIST1res(self, data):
        if hasattr(self, 'filter_IO_CONTEXTS_LIST1res'):
            data = getattr(self, 'filter_IO_CONTEXTS_LIST1res')(data)
        if data.iclr_status is None:
            raise TypeError('data.iclr_status == None')
        self.pack_probe_stat1(data.iclr_status)
        if data.iclr_status == const.PROBE1_OK:
            if data.iclr_resok is None:
                raise TypeError('data.iclr_resok == None')
            self.pack_IO_CONTEXTS_LIST1resok(data.iclr_resok)
        else:
            pass

    def pack_FD_INFOS_LIST1args(self, data):
        if hasattr(self, 'filter_FD_INFOS_LIST1args'):
            data = getattr(self, 'filter_FD_INFOS_LIST1args')(data)
        if data.fila_fd is None:
            raise TypeError('data.fila_fd == None')
        self.pack_int(data.fila_fd)

    def pack_FD_INFOS_LIST1resok(self, data):
        if hasattr(self, 'filter_FD_INFOS_LIST1resok'):
            data = getattr(self, 'filter_FD_INFOS_LIST1resok')(data)
        if data.filr_pf is None:
            raise TypeError('data.filr_pf == None')
        self.pack_array(data.filr_pf, self.pack_probe_fd1)

    def pack_FD_INFOS_LIST1res(self, data):
        if hasattr(self, 'filter_FD_INFOS_LIST1res'):
            data = getattr(self, 'filter_FD_INFOS_LIST1res')(data)
        if data.filr_status is None:
            raise TypeError('data.filr_status == None')
        self.pack_probe_stat1(data.filr_status)
        if data.filr_status == const.PROBE1_OK:
            if data.filr_resok is None:
                raise TypeError('data.filr_resok == None')
            self.pack_FD_INFOS_LIST1resok(data.filr_resok)
        else:
            pass

    def pack_probe_storage_type1(self, data):
        if hasattr(self, 'filter_probe_storage_type1'):
            data = getattr(self, 'filter_probe_storage_type1')(data)
        if self.check_enum and data not in [const.PROBE1_STORAGE_RAM, const.PROBE1_STORAGE_POSIX, const.PROBE1_STORAGE_ROCKSDB, const.PROBE1_STORAGE_FUSE]:
            raise XDRError('value=%s not in enum probe_storage_type1' % data)
        self.pack_int(data)

    def pack_probe_sb_lifecycle1(self, data):
        if hasattr(self, 'filter_probe_sb_lifecycle1'):
            data = getattr(self, 'filter_probe_sb_lifecycle1')(data)
        if self.check_enum and data not in [const.PROBE1_SB_CREATED, const.PROBE1_SB_MOUNTED, const.PROBE1_SB_UNMOUNTED, const.PROBE1_SB_DESTROYED]:
            raise XDRError('value=%s not in enum probe_sb_lifecycle1' % data)
        self.pack_int(data)

    def pack_probe_auth_flavor1(self, data):
        if hasattr(self, 'filter_probe_auth_flavor1'):
            data = getattr(self, 'filter_probe_auth_flavor1')(data)
        if self.check_enum and data not in [const.PROBE1_AUTH_SYS, const.PROBE1_AUTH_KRB5, const.PROBE1_AUTH_KRB5I, const.PROBE1_AUTH_KRB5P, const.PROBE1_AUTH_TLS]:
            raise XDRError('value=%s not in enum probe_auth_flavor1' % data)
        self.pack_int(data)

    def pack_probe_sb_info1(self, data):
        if hasattr(self, 'filter_probe_sb_info1'):
            data = getattr(self, 'filter_probe_sb_info1')(data)
        if data.psi_id is None:
            raise TypeError('data.psi_id == None')
        self.pack_uhyper(data.psi_id)
        if data.psi_uuid is None:
            raise TypeError('data.psi_uuid == None')
        self.pack_fopaque(16, data.psi_uuid)
        if data.psi_path is None:
            raise TypeError('data.psi_path == None')
        self.pack_string(data.psi_path)
        if data.psi_state is None:
            raise TypeError('data.psi_state == None')
        self.pack_probe_sb_lifecycle1(data.psi_state)
        if data.psi_storage_type is None:
            raise TypeError('data.psi_storage_type == None')
        self.pack_probe_storage_type1(data.psi_storage_type)
        if data.psi_flavors is None:
            raise TypeError('data.psi_flavors == None')
        if len(data.psi_flavors) > const.PROBE1_MAX_FLAVORS and self.check_array:
            raise XDRError('array length too long for data.psi_flavors')
        self.pack_array(data.psi_flavors, self.pack_probe_auth_flavor1)
        if data.psi_bytes_max is None:
            raise TypeError('data.psi_bytes_max == None')
        self.pack_uhyper(data.psi_bytes_max)
        if data.psi_bytes_used is None:
            raise TypeError('data.psi_bytes_used == None')
        self.pack_uhyper(data.psi_bytes_used)
        if data.psi_inodes_max is None:
            raise TypeError('data.psi_inodes_max == None')
        self.pack_uhyper(data.psi_inodes_max)
        if data.psi_inodes_used is None:
            raise TypeError('data.psi_inodes_used == None')
        self.pack_uhyper(data.psi_inodes_used)

    def pack_SB_LIST1resok(self, data):
        if hasattr(self, 'filter_SB_LIST1resok'):
            data = getattr(self, 'filter_SB_LIST1resok')(data)
        if data.slr_sbs is None:
            raise TypeError('data.slr_sbs == None')
        self.pack_array(data.slr_sbs, self.pack_probe_sb_info1)

    def pack_SB_LIST1res(self, data):
        if hasattr(self, 'filter_SB_LIST1res'):
            data = getattr(self, 'filter_SB_LIST1res')(data)
        if data.slr_status is None:
            raise TypeError('data.slr_status == None')
        self.pack_probe_stat1(data.slr_status)
        if data.slr_status == const.PROBE1_OK:
            if data.slr_resok is None:
                raise TypeError('data.slr_resok == None')
            self.pack_SB_LIST1resok(data.slr_resok)
        else:
            pass

    def pack_SB_CREATE1args(self, data):
        if hasattr(self, 'filter_SB_CREATE1args'):
            data = getattr(self, 'filter_SB_CREATE1args')(data)
        if data.sca_path is None:
            raise TypeError('data.sca_path == None')
        self.pack_string(data.sca_path)
        if data.sca_storage_type is None:
            raise TypeError('data.sca_storage_type == None')
        self.pack_probe_storage_type1(data.sca_storage_type)

    def pack_SB_CREATE1res(self, data):
        if hasattr(self, 'filter_SB_CREATE1res'):
            data = getattr(self, 'filter_SB_CREATE1res')(data)
        if data.scr_status is None:
            raise TypeError('data.scr_status == None')
        self.pack_probe_stat1(data.scr_status)
        if data.scr_status == const.PROBE1_OK:
            if data.scr_resok is None:
                raise TypeError('data.scr_resok == None')
            self.pack_probe_sb_info1(data.scr_resok)
        else:
            pass

    def pack_SB_MOUNT1args(self, data):
        if hasattr(self, 'filter_SB_MOUNT1args'):
            data = getattr(self, 'filter_SB_MOUNT1args')(data)
        if data.sma_id is None:
            raise TypeError('data.sma_id == None')
        self.pack_uhyper(data.sma_id)
        if data.sma_path is None:
            raise TypeError('data.sma_path == None')
        self.pack_string(data.sma_path)

    def pack_SB_UNMOUNT1args(self, data):
        if hasattr(self, 'filter_SB_UNMOUNT1args'):
            data = getattr(self, 'filter_SB_UNMOUNT1args')(data)
        if data.sua_id is None:
            raise TypeError('data.sua_id == None')
        self.pack_uhyper(data.sua_id)

    def pack_SB_DESTROY1args(self, data):
        if hasattr(self, 'filter_SB_DESTROY1args'):
            data = getattr(self, 'filter_SB_DESTROY1args')(data)
        if data.sda_id is None:
            raise TypeError('data.sda_id == None')
        self.pack_uhyper(data.sda_id)

    def pack_SB_GET1args(self, data):
        if hasattr(self, 'filter_SB_GET1args'):
            data = getattr(self, 'filter_SB_GET1args')(data)
        if data.sga_id is None:
            raise TypeError('data.sga_id == None')
        self.pack_uhyper(data.sga_id)

    def pack_SB_GET1res(self, data):
        if hasattr(self, 'filter_SB_GET1res'):
            data = getattr(self, 'filter_SB_GET1res')(data)
        if data.sgr_status is None:
            raise TypeError('data.sgr_status == None')
        self.pack_probe_stat1(data.sgr_status)
        if data.sgr_status == const.PROBE1_OK:
            if data.sgr_resok is None:
                raise TypeError('data.sgr_resok == None')
            self.pack_probe_sb_info1(data.sgr_resok)
        else:
            pass

    def pack_SB_SET_FLAVORS1args(self, data):
        if hasattr(self, 'filter_SB_SET_FLAVORS1args'):
            data = getattr(self, 'filter_SB_SET_FLAVORS1args')(data)
        if data.sfa_id is None:
            raise TypeError('data.sfa_id == None')
        self.pack_uhyper(data.sfa_id)
        if data.sfa_flavors is None:
            raise TypeError('data.sfa_flavors == None')
        if len(data.sfa_flavors) > const.PROBE1_MAX_FLAVORS and self.check_array:
            raise XDRError('array length too long for data.sfa_flavors')
        self.pack_array(data.sfa_flavors, self.pack_probe_auth_flavor1)

    def pack_SB_LINT_FLAVORS1resok(self, data):
        if hasattr(self, 'filter_SB_LINT_FLAVORS1resok'):
            data = getattr(self, 'filter_SB_LINT_FLAVORS1resok')(data)
        if data.lfr_warnings is None:
            raise TypeError('data.lfr_warnings == None')
        self.pack_uint(data.lfr_warnings)
        if data.lfr_messages is None:
            raise TypeError('data.lfr_messages == None')
        self.pack_string(data.lfr_messages)

    def pack_SB_LINT_FLAVORS1res(self, data):
        if hasattr(self, 'filter_SB_LINT_FLAVORS1res'):
            data = getattr(self, 'filter_SB_LINT_FLAVORS1res')(data)
        if data.lfr_status is None:
            raise TypeError('data.lfr_status == None')
        self.pack_probe_stat1(data.lfr_status)
        if data.lfr_status == const.PROBE1_OK:
            if data.lfr_resok is None:
                raise TypeError('data.lfr_resok == None')
            self.pack_SB_LINT_FLAVORS1resok(data.lfr_resok)
        else:
            pass

    def pack_probe_sb_fs_usage1(self, data):
        if hasattr(self, 'filter_probe_sb_fs_usage1'):
            data = getattr(self, 'filter_probe_sb_fs_usage1')(data)
        if data.sfu_sb_id is None:
            raise TypeError('data.sfu_sb_id == None')
        self.pack_uhyper(data.sfu_sb_id)
        if data.sfu_sb_path is None:
            raise TypeError('data.sfu_sb_path == None')
        self.pack_string(data.sfu_sb_path)
        if data.sfu_total_bytes is None:
            raise TypeError('data.sfu_total_bytes == None')
        self.pack_uhyper(data.sfu_total_bytes)
        if data.sfu_free_bytes is None:
            raise TypeError('data.sfu_free_bytes == None')
        self.pack_uhyper(data.sfu_free_bytes)
        if data.sfu_used_bytes is None:
            raise TypeError('data.sfu_used_bytes == None')
        self.pack_uhyper(data.sfu_used_bytes)
        if data.sfu_total_files is None:
            raise TypeError('data.sfu_total_files == None')
        self.pack_uhyper(data.sfu_total_files)
        if data.sfu_free_files is None:
            raise TypeError('data.sfu_free_files == None')
        self.pack_uhyper(data.sfu_free_files)
        if data.sfu_used_files is None:
            raise TypeError('data.sfu_used_files == None')
        self.pack_uhyper(data.sfu_used_files)

    def pack_FS_USAGE1resok(self, data):
        if hasattr(self, 'filter_FS_USAGE1resok'):
            data = getattr(self, 'filter_FS_USAGE1resok')(data)
        if data.fur_total_bytes is None:
            raise TypeError('data.fur_total_bytes == None')
        self.pack_uhyper(data.fur_total_bytes)
        if data.fur_free_bytes is None:
            raise TypeError('data.fur_free_bytes == None')
        self.pack_uhyper(data.fur_free_bytes)
        if data.fur_used_bytes is None:
            raise TypeError('data.fur_used_bytes == None')
        self.pack_uhyper(data.fur_used_bytes)
        if data.fur_total_files is None:
            raise TypeError('data.fur_total_files == None')
        self.pack_uhyper(data.fur_total_files)
        if data.fur_free_files is None:
            raise TypeError('data.fur_free_files == None')
        self.pack_uhyper(data.fur_free_files)
        if data.fur_used_files is None:
            raise TypeError('data.fur_used_files == None')
        self.pack_uhyper(data.fur_used_files)
        if data.fur_per_sb is None:
            raise TypeError('data.fur_per_sb == None')
        self.pack_array(data.fur_per_sb, self.pack_probe_sb_fs_usage1)

    def pack_FS_USAGE1res(self, data):
        if hasattr(self, 'filter_FS_USAGE1res'):
            data = getattr(self, 'filter_FS_USAGE1res')(data)
        if data.fur_status is None:
            raise TypeError('data.fur_status == None')
        self.pack_probe_stat1(data.fur_status)
        if data.fur_status == const.PROBE1_OK:
            if data.fur_resok is None:
                raise TypeError('data.fur_resok == None')
            self.pack_FS_USAGE1resok(data.fur_resok)
        else:
            pass

    def pack_probe_nfs4_op1(self, data):
        if hasattr(self, 'filter_probe_nfs4_op1'):
            data = getattr(self, 'filter_probe_nfs4_op1')(data)
        if data.pno_op is None:
            raise TypeError('data.pno_op == None')
        self.pack_uint(data.pno_op)
        if data.pno_name is None:
            raise TypeError('data.pno_name == None')
        self.pack_string(data.pno_name)
        if data.pno_calls is None:
            raise TypeError('data.pno_calls == None')
        self.pack_uhyper(data.pno_calls)
        if data.pno_errors is None:
            raise TypeError('data.pno_errors == None')
        self.pack_uhyper(data.pno_errors)
        if data.pno_bytes_in is None:
            raise TypeError('data.pno_bytes_in == None')
        self.pack_uhyper(data.pno_bytes_in)
        if data.pno_bytes_out is None:
            raise TypeError('data.pno_bytes_out == None')
        self.pack_uhyper(data.pno_bytes_out)
        if data.pno_duration_total is None:
            raise TypeError('data.pno_duration_total == None')
        self.pack_uhyper(data.pno_duration_total)
        if data.pno_duration_max is None:
            raise TypeError('data.pno_duration_max == None')
        self.pack_uhyper(data.pno_duration_max)

    def pack_probe_sb_nfs4_op_stats1(self, data):
        if hasattr(self, 'filter_probe_sb_nfs4_op_stats1'):
            data = getattr(self, 'filter_probe_sb_nfs4_op_stats1')(data)
        if data.sns_sb_id is None:
            raise TypeError('data.sns_sb_id == None')
        self.pack_uhyper(data.sns_sb_id)
        if data.sns_sb_path is None:
            raise TypeError('data.sns_sb_path == None')
        self.pack_string(data.sns_sb_path)
        if data.sns_ops is None:
            raise TypeError('data.sns_ops == None')
        self.pack_array(data.sns_ops, self.pack_probe_nfs4_op1)

    def pack_NFS4_OP_STATS1resok(self, data):
        if hasattr(self, 'filter_NFS4_OP_STATS1resok'):
            data = getattr(self, 'filter_NFS4_OP_STATS1resok')(data)
        if data.nosr_ops is None:
            raise TypeError('data.nosr_ops == None')
        self.pack_array(data.nosr_ops, self.pack_probe_nfs4_op1)
        if data.nosr_per_sb is None:
            raise TypeError('data.nosr_per_sb == None')
        self.pack_array(data.nosr_per_sb, self.pack_probe_sb_nfs4_op_stats1)

    def pack_NFS4_OP_STATS1res(self, data):
        if hasattr(self, 'filter_NFS4_OP_STATS1res'):
            data = getattr(self, 'filter_NFS4_OP_STATS1res')(data)
        if data.nosr_status is None:
            raise TypeError('data.nosr_status == None')
        self.pack_probe_stat1(data.nosr_status)
        if data.nosr_status == const.PROBE1_OK:
            if data.nosr_resok is None:
                raise TypeError('data.nosr_resok == None')
            self.pack_NFS4_OP_STATS1resok(data.nosr_resok)
        else:
            pass

    def pack_probe_layout_error1(self, data):
        if hasattr(self, 'filter_probe_layout_error1'):
            data = getattr(self, 'filter_probe_layout_error1')(data)
        if data.ple_id is None:
            raise TypeError('data.ple_id == None')
        self.pack_uint(data.ple_id)
        if data.ple_name is None:
            raise TypeError('data.ple_name == None')
        self.pack_string(data.ple_name)
        if data.ple_total is None:
            raise TypeError('data.ple_total == None')
        self.pack_uhyper(data.ple_total)
        if data.ple_access is None:
            raise TypeError('data.ple_access == None')
        self.pack_uhyper(data.ple_access)
        if data.ple_io is None:
            raise TypeError('data.ple_io == None')
        self.pack_uhyper(data.ple_io)
        if data.ple_other is None:
            raise TypeError('data.ple_other == None')
        self.pack_uhyper(data.ple_other)

    def pack_LAYOUT_ERRORS1resok(self, data):
        if hasattr(self, 'filter_LAYOUT_ERRORS1resok'):
            data = getattr(self, 'filter_LAYOUT_ERRORS1resok')(data)
        if data.ler_global is None:
            raise TypeError('data.ler_global == None')
        self.pack_probe_layout_error1(data.ler_global)
        if data.ler_dstores is None:
            raise TypeError('data.ler_dstores == None')
        self.pack_array(data.ler_dstores, self.pack_probe_layout_error1)
        if data.ler_clients is None:
            raise TypeError('data.ler_clients == None')
        self.pack_array(data.ler_clients, self.pack_probe_layout_error1)
        if data.ler_sbs is None:
            raise TypeError('data.ler_sbs == None')
        self.pack_array(data.ler_sbs, self.pack_probe_layout_error1)

    def pack_LAYOUT_ERRORS1res(self, data):
        if hasattr(self, 'filter_LAYOUT_ERRORS1res'):
            data = getattr(self, 'filter_LAYOUT_ERRORS1res')(data)
        if data.ler_status is None:
            raise TypeError('data.ler_status == None')
        self.pack_probe_stat1(data.ler_status)
        if data.ler_status == const.PROBE1_OK:
            if data.ler_resok is None:
                raise TypeError('data.ler_resok == None')
            self.pack_LAYOUT_ERRORS1resok(data.ler_resok)
        else:
            pass

    def pack_probe_id_domain1(self, data):
        if hasattr(self, 'filter_probe_id_domain1'):
            data = getattr(self, 'filter_probe_id_domain1')(data)
        if data.pid_index is None:
            raise TypeError('data.pid_index == None')
        self.pack_uint32_t(data.pid_index)
        if data.pid_name is None:
            raise TypeError('data.pid_name == None')
        if len(data.pid_name) > 256 and self.check_array:
            raise XDRError('array length too long for data.pid_name')
        self.pack_string(data.pid_name)
        if data.pid_type is None:
            raise TypeError('data.pid_type == None')
        self.pack_uint32_t(data.pid_type)

    def pack_IDENTITY_DOMAIN_LIST1resok(self, data):
        if hasattr(self, 'filter_IDENTITY_DOMAIN_LIST1resok'):
            data = getattr(self, 'filter_IDENTITY_DOMAIN_LIST1resok')(data)
        if data.idl_domains is None:
            raise TypeError('data.idl_domains == None')
        if len(data.idl_domains) > 64 and self.check_array:
            raise XDRError('array length too long for data.idl_domains')
        self.pack_array(data.idl_domains, self.pack_probe_id_domain1)

    def pack_IDENTITY_DOMAIN_LIST1res(self, data):
        if hasattr(self, 'filter_IDENTITY_DOMAIN_LIST1res'):
            data = getattr(self, 'filter_IDENTITY_DOMAIN_LIST1res')(data)
        if data.idl_status is None:
            raise TypeError('data.idl_status == None')
        self.pack_probe_stat1(data.idl_status)
        if data.idl_status == const.PROBE1_OK:
            if data.idl_resok is None:
                raise TypeError('data.idl_resok == None')
            self.pack_IDENTITY_DOMAIN_LIST1resok(data.idl_resok)
        else:
            pass

    def pack_probe_id_mapping1(self, data):
        if hasattr(self, 'filter_probe_id_mapping1'):
            data = getattr(self, 'filter_probe_id_mapping1')(data)
        if data.pim_from is None:
            raise TypeError('data.pim_from == None')
        self.pack_uint64_t(data.pim_from)
        if data.pim_to is None:
            raise TypeError('data.pim_to == None')
        self.pack_uint64_t(data.pim_to)
        if data.pim_name is None:
            raise TypeError('data.pim_name == None')
        if len(data.pim_name) > 256 and self.check_array:
            raise XDRError('array length too long for data.pim_name')
        self.pack_string(data.pim_name)

    def pack_IDENTITY_MAP_LIST1resok(self, data):
        if hasattr(self, 'filter_IDENTITY_MAP_LIST1resok'):
            data = getattr(self, 'filter_IDENTITY_MAP_LIST1resok')(data)
        if data.iml_mappings is None:
            raise TypeError('data.iml_mappings == None')
        if len(data.iml_mappings) > 1024 and self.check_array:
            raise XDRError('array length too long for data.iml_mappings')
        self.pack_array(data.iml_mappings, self.pack_probe_id_mapping1)

    def pack_IDENTITY_MAP_LIST1res(self, data):
        if hasattr(self, 'filter_IDENTITY_MAP_LIST1res'):
            data = getattr(self, 'filter_IDENTITY_MAP_LIST1res')(data)
        if data.iml_status is None:
            raise TypeError('data.iml_status == None')
        self.pack_probe_stat1(data.iml_status)
        if data.iml_status == const.PROBE1_OK:
            if data.iml_resok is None:
                raise TypeError('data.iml_resok == None')
            self.pack_IDENTITY_MAP_LIST1resok(data.iml_resok)
        else:
            pass

    def pack_IDENTITY_MAP_REMOVE1args(self, data):
        if hasattr(self, 'filter_IDENTITY_MAP_REMOVE1args'):
            data = getattr(self, 'filter_IDENTITY_MAP_REMOVE1args')(data)
        if data.imr_from is None:
            raise TypeError('data.imr_from == None')
        self.pack_uint64_t(data.imr_from)


class PROBE1_XDRUnpacker(xdrlib.Unpacker):
    def __init__(self, data, check_enum=True, check_array=True):
        xdrlib.Unpacker.__init__(self, data)
        self.check_enum = check_enum
        self.check_array = check_array

    unpack_int = xdrlib.Unpacker.unpack_int
    unpack_uint = xdrlib.Unpacker.unpack_uint
    unpack_unsigned = xdrlib.Unpacker.unpack_uint
    unpack_hyper = xdrlib.Unpacker.unpack_hyper
    unpack_uhyper = xdrlib.Unpacker.unpack_uhyper
    unpack_float = xdrlib.Unpacker.unpack_float
    unpack_double = xdrlib.Unpacker.unpack_double
    unpack_quadruple = xdrlib.Unpacker.unpack_double
    unpack_bool = xdrlib.Unpacker.unpack_bool
    unpack_opaque = xdrlib.Unpacker.unpack_opaque
    unpack_string = xdrlib.Unpacker.unpack_string
    def unpack_probe1_address_string(self):
        data = self.unpack_fopaque(const.PROBE1_ADDR_LEN)
        if hasattr(self, 'filter_probe1_address_string'):
            data = getattr(self, 'filter_probe1_address_string')(data)
        return data

    def unpack_probe_time1(self):
        data = types.probe_time1()
        data.seconds = self.unpack_uint()
        data.nseconds = self.unpack_uint()
        if hasattr(self, 'filter_probe_time1'):
            data = getattr(self, 'filter_probe_time1')(data)
        return data

    def unpack_probe_stat1(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.PROBE1_OK, const.PROBE1ERR_PERM, const.PROBE1ERR_NOENT, const.PROBE1ERR_IO, const.PROBE1ERR_ENXIO, const.PROBE1ERR_BADF, const.PROBE1ERR_AGAIN, const.PROBE1ERR_NOMEM, const.PROBE1ERR_ACCES, const.PROBE1ERR_BUSY, const.PROBE1ERR_EXIST, const.PROBE1ERR_NOTDIR, const.PROBE1ERR_INVAL, const.PROBE1ERR_NOSPC, const.PROBE1ERR_STALE, const.PROBE1ERR_ALREADY, const.PROBE1ERR_NOTSUPP, const.PROBE1ERR_SERVERFAULT, const.PROBE1ERR_DELAY, const.PROBE1ERR_BADXDR, const.PROBE1ERR_BADNAME]:
            raise XDRError('value=%s not in enum probe_stat1' % data)
        if hasattr(self, 'filter_probe_stat1'):
            data = getattr(self, 'filter_probe_stat1')(data)
        return data

    def unpack_probe_op1(self):
        data = types.probe_op1()
        data.po_op = self.unpack_uint()
        data.po_name = self.unpack_string()
        data.po_calls = self.unpack_uhyper()
        data.po_errors = self.unpack_uhyper()
        data.po_max_duration = self.unpack_uhyper()
        data.po_total_duration = self.unpack_uhyper()
        data.po_bucket_1ms = self.unpack_uhyper()
        data.po_bucket_10ms = self.unpack_uhyper()
        data.po_bucket_100ms = self.unpack_uhyper()
        data.po_bucket_1s = self.unpack_uhyper()
        data.po_bucket_10s = self.unpack_uhyper()
        data.po_bucket_rest = self.unpack_uhyper()
        data.po_median_ns = self.unpack_uhyper()
        data.po_p90_ns = self.unpack_uhyper()
        data.po_p99_ns = self.unpack_uhyper()
        data.po_p999_ns = self.unpack_uhyper()
        data.po_min_ns = self.unpack_uhyper()
        data.po_max_ns = self.unpack_uhyper()
        data.po_mean_ns = self.unpack_uhyper()
        if hasattr(self, 'filter_probe_op1'):
            data = getattr(self, 'filter_probe_op1')(data)
        return data

    def unpack_probe_program1(self):
        data = types.probe_program1()
        data.pp_program = self.unpack_uint()
        data.pp_version = self.unpack_uint()
        data.pp_count = self.unpack_uhyper()
        data.pp_replied_errors = self.unpack_uhyper()
        data.pp_rejected_errors = self.unpack_uhyper()
        data.pp_accepted_errors = self.unpack_uhyper()
        data.pp_authed_errors = self.unpack_uhyper()
        data.pp_ops = self.unpack_array(self.unpack_probe_op1)
        if hasattr(self, 'filter_probe_program1'):
            data = getattr(self, 'filter_probe_program1')(data)
        return data

    def unpack_STATS_GATHER1args(self):
        data = types.STATS_GATHER1args()
        data.psga_program = self.unpack_uint()
        data.psga_version = self.unpack_uint()
        if hasattr(self, 'filter_STATS_GATHER1args'):
            data = getattr(self, 'filter_STATS_GATHER1args')(data)
        return data

    def unpack_STATS_GATHER1resok(self):
        data = types.STATS_GATHER1resok()
        data.psgr_program = self.unpack_probe_program1()
        if hasattr(self, 'filter_STATS_GATHER1resok'):
            data = getattr(self, 'filter_STATS_GATHER1resok')(data)
        return data

    def unpack_STATS_GATHER1res(self):
        data = types.STATS_GATHER1res()
        data.psgr_status = self.unpack_probe_stat1()
        if data.psgr_status == const.PROBE1_OK:
            data.psgr_resok = self.unpack_STATS_GATHER1resok()
        else:
            pass
        if hasattr(self, 'filter_STATS_GATHER1res'):
            data = getattr(self, 'filter_STATS_GATHER1res')(data)
        return data

    def unpack_CONTEXT1resok(self):
        data = types.CONTEXT1resok()
        data.pcr_created = self.unpack_uhyper()
        data.pcr_freed = self.unpack_uhyper()
        data.pcr_active_cancelled = self.unpack_uhyper()
        data.pcr_active_destroyed = self.unpack_uhyper()
        data.pcr_cancelled_freed = self.unpack_uhyper()
        data.pcr_destroyed_freed = self.unpack_uhyper()
        if hasattr(self, 'filter_CONTEXT1resok'):
            data = getattr(self, 'filter_CONTEXT1resok')(data)
        return data

    def unpack_CONTEXT1res(self):
        data = types.CONTEXT1res()
        data.pcr_status = self.unpack_probe_stat1()
        if data.pcr_status == const.PROBE1_OK:
            data.pcr_resok = self.unpack_CONTEXT1resok()
        else:
            pass
        if hasattr(self, 'filter_CONTEXT1res'):
            data = getattr(self, 'filter_CONTEXT1res')(data)
        return data

    unpack_probe_dump1 = unpack_uint

    def unpack_probe_trace_category1(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.PROBE1_TRACE_CAT_GENERAL, const.PROBE1_TRACE_CAT_IO, const.PROBE1_TRACE_CAT_RPC, const.PROBE1_TRACE_CAT_NFS, const.PROBE1_TRACE_CAT_NLM, const.PROBE1_TRACE_CAT_FS, const.PROBE1_TRACE_CAT_LOG, const.PROBE1_TRACE_CAT_SECURITY, const.PROBE1_TRACE_CAT_LIFECYCLE, const.PROBE1_TRACE_CAT_ALL]:
            raise XDRError('value=%s not in enum probe_trace_category1' % data)
        if hasattr(self, 'filter_probe_trace_category1'):
            data = getattr(self, 'filter_probe_trace_category1')(data)
        return data

    def unpack_TRACE_SET1args(self):
        data = types.TRACE_SET1args()
        data.tsa_cat = self.unpack_probe_trace_category1()
        data.tsa_set = self.unpack_uint()
        if hasattr(self, 'filter_TRACE_SET1args'):
            data = getattr(self, 'filter_TRACE_SET1args')(data)
        return data

    def unpack_TRACES_LIST1args(self):
        data = types.TRACES_LIST1args()
        data.tla_cat = self.unpack_probe_trace_category1()
        if hasattr(self, 'filter_TRACES_LIST1args'):
            data = getattr(self, 'filter_TRACES_LIST1args')(data)
        return data

    def unpack_probe_trace_list1(self):
        data = types.probe_trace_list1()
        data.ptl_cat = self.unpack_probe_trace_category1()
        data.ptl_set = self.unpack_uint()
        if hasattr(self, 'filter_probe_trace_list1'):
            data = getattr(self, 'filter_probe_trace_list1')(data)
        return data

    def unpack_TRACES_LIST1resok(self):
        data = types.TRACES_LIST1resok()
        data.tlr_list = self.unpack_array(self.unpack_probe_trace_list1)
        if hasattr(self, 'filter_TRACES_LIST1resok'):
            data = getattr(self, 'filter_TRACES_LIST1resok')(data)
        return data

    def unpack_TRACES_LIST1res(self):
        data = types.TRACES_LIST1res()
        data.tlr_status = self.unpack_probe_stat1()
        if data.tlr_status == const.PROBE1_OK:
            data.tlr_resok = self.unpack_TRACES_LIST1resok()
        else:
            pass
        if hasattr(self, 'filter_TRACES_LIST1res'):
            data = getattr(self, 'filter_TRACES_LIST1res')(data)
        return data

    def unpack_HEARTBEAT1args(self):
        data = types.HEARTBEAT1args()
        data.hba_period = self.unpack_uint()
        data.hba_period_set = self.unpack_uint()
        if hasattr(self, 'filter_HEARTBEAT1args'):
            data = getattr(self, 'filter_HEARTBEAT1args')(data)
        return data

    def unpack_HEARTBEAT1resok(self):
        data = types.HEARTBEAT1resok()
        data.hbr_period = self.unpack_uint()
        if hasattr(self, 'filter_HEARTBEAT1resok'):
            data = getattr(self, 'filter_HEARTBEAT1resok')(data)
        return data

    def unpack_HEARTBEAT1res(self):
        data = types.HEARTBEAT1res()
        data.hbr_status = self.unpack_probe_stat1()
        if data.hbr_status == const.PROBE1_OK:
            data.hbr_resok = self.unpack_HEARTBEAT1resok()
        else:
            pass
        if hasattr(self, 'filter_HEARTBEAT1res'):
            data = getattr(self, 'filter_HEARTBEAT1res')(data)
        return data

    def unpack_probe_op_type1(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.PROBE1_OP_TYPE_ACCEPT, const.PROBE1_OP_TYPE_READ, const.PROBE1_OP_TYPE_WRITE, const.PROBE1_OP_TYPE_CONNECT, const.PROBE1_OP_TYPE_RPC_REQ, const.PROBE1_OP_TYPE_HEARTBEAT, const.PROBE1_OP_TYPE_ALL]:
            raise XDRError('value=%s not in enum probe_op_type1' % data)
        if hasattr(self, 'filter_probe_op_type1'):
            data = getattr(self, 'filter_probe_op_type1')(data)
        return data

    def unpack_probe_io_context1(self):
        data = types.probe_io_context1()
        data.pic_op_type = self.unpack_probe_op_type1()
        data.pic_fd = self.unpack_int()
        data.pic_id = self.unpack_uint()
        data.pic_xid = self.unpack_uint()
        data.pic_buffer_len = self.unpack_uhyper()
        data.pic_position = self.unpack_uhyper()
        data.pic_expected_len = self.unpack_uhyper()
        data.pic_state = self.unpack_uhyper()
        data.pic_count = self.unpack_uhyper()
        data.pic_action_time = self.unpack_probe_time1()
        if hasattr(self, 'filter_probe_io_context1'):
            data = getattr(self, 'filter_probe_io_context1')(data)
        return data

    def unpack_probe_fd1(self):
        data = types.probe_fd1()
        data.pf_fd = self.unpack_int()
        data.pf_server_port = self.unpack_uint()
        data.pf_client = self.unpack_probe1_address_string()
        if hasattr(self, 'filter_probe_fd1'):
            data = getattr(self, 'filter_probe_fd1')(data)
        return data

    def unpack_IO_CONTEXTS_LIST1args(self):
        data = types.IO_CONTEXTS_LIST1args()
        data.icla_fd = self.unpack_int()
        data.icla_op = self.unpack_probe_op_type1()
        data.icla_state = self.unpack_uhyper()
        if hasattr(self, 'filter_IO_CONTEXTS_LIST1args'):
            data = getattr(self, 'filter_IO_CONTEXTS_LIST1args')(data)
        return data

    def unpack_IO_CONTEXTS_LIST1resok(self):
        data = types.IO_CONTEXTS_LIST1resok()
        data.iclr_pic = self.unpack_array(self.unpack_probe_io_context1)
        data.iclr_now = self.unpack_probe_time1()
        if hasattr(self, 'filter_IO_CONTEXTS_LIST1resok'):
            data = getattr(self, 'filter_IO_CONTEXTS_LIST1resok')(data)
        return data

    def unpack_IO_CONTEXTS_LIST1res(self):
        data = types.IO_CONTEXTS_LIST1res()
        data.iclr_status = self.unpack_probe_stat1()
        if data.iclr_status == const.PROBE1_OK:
            data.iclr_resok = self.unpack_IO_CONTEXTS_LIST1resok()
        else:
            pass
        if hasattr(self, 'filter_IO_CONTEXTS_LIST1res'):
            data = getattr(self, 'filter_IO_CONTEXTS_LIST1res')(data)
        return data

    def unpack_FD_INFOS_LIST1args(self):
        data = types.FD_INFOS_LIST1args()
        data.fila_fd = self.unpack_int()
        if hasattr(self, 'filter_FD_INFOS_LIST1args'):
            data = getattr(self, 'filter_FD_INFOS_LIST1args')(data)
        return data

    def unpack_FD_INFOS_LIST1resok(self):
        data = types.FD_INFOS_LIST1resok()
        data.filr_pf = self.unpack_array(self.unpack_probe_fd1)
        if hasattr(self, 'filter_FD_INFOS_LIST1resok'):
            data = getattr(self, 'filter_FD_INFOS_LIST1resok')(data)
        return data

    def unpack_FD_INFOS_LIST1res(self):
        data = types.FD_INFOS_LIST1res()
        data.filr_status = self.unpack_probe_stat1()
        if data.filr_status == const.PROBE1_OK:
            data.filr_resok = self.unpack_FD_INFOS_LIST1resok()
        else:
            pass
        if hasattr(self, 'filter_FD_INFOS_LIST1res'):
            data = getattr(self, 'filter_FD_INFOS_LIST1res')(data)
        return data

    def unpack_probe_storage_type1(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.PROBE1_STORAGE_RAM, const.PROBE1_STORAGE_POSIX, const.PROBE1_STORAGE_ROCKSDB, const.PROBE1_STORAGE_FUSE]:
            raise XDRError('value=%s not in enum probe_storage_type1' % data)
        if hasattr(self, 'filter_probe_storage_type1'):
            data = getattr(self, 'filter_probe_storage_type1')(data)
        return data

    def unpack_probe_sb_lifecycle1(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.PROBE1_SB_CREATED, const.PROBE1_SB_MOUNTED, const.PROBE1_SB_UNMOUNTED, const.PROBE1_SB_DESTROYED]:
            raise XDRError('value=%s not in enum probe_sb_lifecycle1' % data)
        if hasattr(self, 'filter_probe_sb_lifecycle1'):
            data = getattr(self, 'filter_probe_sb_lifecycle1')(data)
        return data

    def unpack_probe_auth_flavor1(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.PROBE1_AUTH_SYS, const.PROBE1_AUTH_KRB5, const.PROBE1_AUTH_KRB5I, const.PROBE1_AUTH_KRB5P, const.PROBE1_AUTH_TLS]:
            raise XDRError('value=%s not in enum probe_auth_flavor1' % data)
        if hasattr(self, 'filter_probe_auth_flavor1'):
            data = getattr(self, 'filter_probe_auth_flavor1')(data)
        return data

    def unpack_probe_sb_info1(self):
        data = types.probe_sb_info1()
        data.psi_id = self.unpack_uhyper()
        data.psi_uuid = self.unpack_fopaque(16)
        data.psi_path = self.unpack_string()
        data.psi_state = self.unpack_probe_sb_lifecycle1()
        data.psi_storage_type = self.unpack_probe_storage_type1()
        data.psi_flavors = self.unpack_array(self.unpack_probe_auth_flavor1)
        if len(data.psi_flavors) > const.PROBE1_MAX_FLAVORS and self.check_array:
            raise XDRError('array length too long for data.psi_flavors')
        data.psi_bytes_max = self.unpack_uhyper()
        data.psi_bytes_used = self.unpack_uhyper()
        data.psi_inodes_max = self.unpack_uhyper()
        data.psi_inodes_used = self.unpack_uhyper()
        if hasattr(self, 'filter_probe_sb_info1'):
            data = getattr(self, 'filter_probe_sb_info1')(data)
        return data

    def unpack_SB_LIST1resok(self):
        data = types.SB_LIST1resok()
        data.slr_sbs = self.unpack_array(self.unpack_probe_sb_info1)
        if hasattr(self, 'filter_SB_LIST1resok'):
            data = getattr(self, 'filter_SB_LIST1resok')(data)
        return data

    def unpack_SB_LIST1res(self):
        data = types.SB_LIST1res()
        data.slr_status = self.unpack_probe_stat1()
        if data.slr_status == const.PROBE1_OK:
            data.slr_resok = self.unpack_SB_LIST1resok()
        else:
            pass
        if hasattr(self, 'filter_SB_LIST1res'):
            data = getattr(self, 'filter_SB_LIST1res')(data)
        return data

    def unpack_SB_CREATE1args(self):
        data = types.SB_CREATE1args()
        data.sca_path = self.unpack_string()
        data.sca_storage_type = self.unpack_probe_storage_type1()
        if hasattr(self, 'filter_SB_CREATE1args'):
            data = getattr(self, 'filter_SB_CREATE1args')(data)
        return data

    def unpack_SB_CREATE1res(self):
        data = types.SB_CREATE1res()
        data.scr_status = self.unpack_probe_stat1()
        if data.scr_status == const.PROBE1_OK:
            data.scr_resok = self.unpack_probe_sb_info1()
        else:
            pass
        if hasattr(self, 'filter_SB_CREATE1res'):
            data = getattr(self, 'filter_SB_CREATE1res')(data)
        return data

    def unpack_SB_MOUNT1args(self):
        data = types.SB_MOUNT1args()
        data.sma_id = self.unpack_uhyper()
        data.sma_path = self.unpack_string()
        if hasattr(self, 'filter_SB_MOUNT1args'):
            data = getattr(self, 'filter_SB_MOUNT1args')(data)
        return data

    def unpack_SB_UNMOUNT1args(self):
        data = types.SB_UNMOUNT1args()
        data.sua_id = self.unpack_uhyper()
        if hasattr(self, 'filter_SB_UNMOUNT1args'):
            data = getattr(self, 'filter_SB_UNMOUNT1args')(data)
        return data

    def unpack_SB_DESTROY1args(self):
        data = types.SB_DESTROY1args()
        data.sda_id = self.unpack_uhyper()
        if hasattr(self, 'filter_SB_DESTROY1args'):
            data = getattr(self, 'filter_SB_DESTROY1args')(data)
        return data

    def unpack_SB_GET1args(self):
        data = types.SB_GET1args()
        data.sga_id = self.unpack_uhyper()
        if hasattr(self, 'filter_SB_GET1args'):
            data = getattr(self, 'filter_SB_GET1args')(data)
        return data

    def unpack_SB_GET1res(self):
        data = types.SB_GET1res()
        data.sgr_status = self.unpack_probe_stat1()
        if data.sgr_status == const.PROBE1_OK:
            data.sgr_resok = self.unpack_probe_sb_info1()
        else:
            pass
        if hasattr(self, 'filter_SB_GET1res'):
            data = getattr(self, 'filter_SB_GET1res')(data)
        return data

    def unpack_SB_SET_FLAVORS1args(self):
        data = types.SB_SET_FLAVORS1args()
        data.sfa_id = self.unpack_uhyper()
        data.sfa_flavors = self.unpack_array(self.unpack_probe_auth_flavor1)
        if len(data.sfa_flavors) > const.PROBE1_MAX_FLAVORS and self.check_array:
            raise XDRError('array length too long for data.sfa_flavors')
        if hasattr(self, 'filter_SB_SET_FLAVORS1args'):
            data = getattr(self, 'filter_SB_SET_FLAVORS1args')(data)
        return data

    def unpack_SB_LINT_FLAVORS1resok(self):
        data = types.SB_LINT_FLAVORS1resok()
        data.lfr_warnings = self.unpack_uint()
        data.lfr_messages = self.unpack_string()
        if hasattr(self, 'filter_SB_LINT_FLAVORS1resok'):
            data = getattr(self, 'filter_SB_LINT_FLAVORS1resok')(data)
        return data

    def unpack_SB_LINT_FLAVORS1res(self):
        data = types.SB_LINT_FLAVORS1res()
        data.lfr_status = self.unpack_probe_stat1()
        if data.lfr_status == const.PROBE1_OK:
            data.lfr_resok = self.unpack_SB_LINT_FLAVORS1resok()
        else:
            pass
        if hasattr(self, 'filter_SB_LINT_FLAVORS1res'):
            data = getattr(self, 'filter_SB_LINT_FLAVORS1res')(data)
        return data

    def unpack_probe_sb_fs_usage1(self):
        data = types.probe_sb_fs_usage1()
        data.sfu_sb_id = self.unpack_uhyper()
        data.sfu_sb_path = self.unpack_string()
        data.sfu_total_bytes = self.unpack_uhyper()
        data.sfu_free_bytes = self.unpack_uhyper()
        data.sfu_used_bytes = self.unpack_uhyper()
        data.sfu_total_files = self.unpack_uhyper()
        data.sfu_free_files = self.unpack_uhyper()
        data.sfu_used_files = self.unpack_uhyper()
        if hasattr(self, 'filter_probe_sb_fs_usage1'):
            data = getattr(self, 'filter_probe_sb_fs_usage1')(data)
        return data

    def unpack_FS_USAGE1resok(self):
        data = types.FS_USAGE1resok()
        data.fur_total_bytes = self.unpack_uhyper()
        data.fur_free_bytes = self.unpack_uhyper()
        data.fur_used_bytes = self.unpack_uhyper()
        data.fur_total_files = self.unpack_uhyper()
        data.fur_free_files = self.unpack_uhyper()
        data.fur_used_files = self.unpack_uhyper()
        data.fur_per_sb = self.unpack_array(self.unpack_probe_sb_fs_usage1)
        if hasattr(self, 'filter_FS_USAGE1resok'):
            data = getattr(self, 'filter_FS_USAGE1resok')(data)
        return data

    def unpack_FS_USAGE1res(self):
        data = types.FS_USAGE1res()
        data.fur_status = self.unpack_probe_stat1()
        if data.fur_status == const.PROBE1_OK:
            data.fur_resok = self.unpack_FS_USAGE1resok()
        else:
            pass
        if hasattr(self, 'filter_FS_USAGE1res'):
            data = getattr(self, 'filter_FS_USAGE1res')(data)
        return data

    def unpack_probe_nfs4_op1(self):
        data = types.probe_nfs4_op1()
        data.pno_op = self.unpack_uint()
        data.pno_name = self.unpack_string()
        data.pno_calls = self.unpack_uhyper()
        data.pno_errors = self.unpack_uhyper()
        data.pno_bytes_in = self.unpack_uhyper()
        data.pno_bytes_out = self.unpack_uhyper()
        data.pno_duration_total = self.unpack_uhyper()
        data.pno_duration_max = self.unpack_uhyper()
        if hasattr(self, 'filter_probe_nfs4_op1'):
            data = getattr(self, 'filter_probe_nfs4_op1')(data)
        return data

    def unpack_probe_sb_nfs4_op_stats1(self):
        data = types.probe_sb_nfs4_op_stats1()
        data.sns_sb_id = self.unpack_uhyper()
        data.sns_sb_path = self.unpack_string()
        data.sns_ops = self.unpack_array(self.unpack_probe_nfs4_op1)
        if hasattr(self, 'filter_probe_sb_nfs4_op_stats1'):
            data = getattr(self, 'filter_probe_sb_nfs4_op_stats1')(data)
        return data

    def unpack_NFS4_OP_STATS1resok(self):
        data = types.NFS4_OP_STATS1resok()
        data.nosr_ops = self.unpack_array(self.unpack_probe_nfs4_op1)
        data.nosr_per_sb = self.unpack_array(self.unpack_probe_sb_nfs4_op_stats1)
        if hasattr(self, 'filter_NFS4_OP_STATS1resok'):
            data = getattr(self, 'filter_NFS4_OP_STATS1resok')(data)
        return data

    def unpack_NFS4_OP_STATS1res(self):
        data = types.NFS4_OP_STATS1res()
        data.nosr_status = self.unpack_probe_stat1()
        if data.nosr_status == const.PROBE1_OK:
            data.nosr_resok = self.unpack_NFS4_OP_STATS1resok()
        else:
            pass
        if hasattr(self, 'filter_NFS4_OP_STATS1res'):
            data = getattr(self, 'filter_NFS4_OP_STATS1res')(data)
        return data

    def unpack_probe_layout_error1(self):
        data = types.probe_layout_error1()
        data.ple_id = self.unpack_uint()
        data.ple_name = self.unpack_string()
        data.ple_total = self.unpack_uhyper()
        data.ple_access = self.unpack_uhyper()
        data.ple_io = self.unpack_uhyper()
        data.ple_other = self.unpack_uhyper()
        if hasattr(self, 'filter_probe_layout_error1'):
            data = getattr(self, 'filter_probe_layout_error1')(data)
        return data

    def unpack_LAYOUT_ERRORS1resok(self):
        data = types.LAYOUT_ERRORS1resok()
        data.ler_global = self.unpack_probe_layout_error1()
        data.ler_dstores = self.unpack_array(self.unpack_probe_layout_error1)
        data.ler_clients = self.unpack_array(self.unpack_probe_layout_error1)
        data.ler_sbs = self.unpack_array(self.unpack_probe_layout_error1)
        if hasattr(self, 'filter_LAYOUT_ERRORS1resok'):
            data = getattr(self, 'filter_LAYOUT_ERRORS1resok')(data)
        return data

    def unpack_LAYOUT_ERRORS1res(self):
        data = types.LAYOUT_ERRORS1res()
        data.ler_status = self.unpack_probe_stat1()
        if data.ler_status == const.PROBE1_OK:
            data.ler_resok = self.unpack_LAYOUT_ERRORS1resok()
        else:
            pass
        if hasattr(self, 'filter_LAYOUT_ERRORS1res'):
            data = getattr(self, 'filter_LAYOUT_ERRORS1res')(data)
        return data

    def unpack_probe_id_domain1(self):
        data = types.probe_id_domain1()
        data.pid_index = self.unpack_uint32_t()
        data.pid_name = self.unpack_string()
        if len(data.pid_name) > 256 and self.check_array:
            raise XDRError('array length too long for data.pid_name')
        data.pid_type = self.unpack_uint32_t()
        if hasattr(self, 'filter_probe_id_domain1'):
            data = getattr(self, 'filter_probe_id_domain1')(data)
        return data

    def unpack_IDENTITY_DOMAIN_LIST1resok(self):
        data = types.IDENTITY_DOMAIN_LIST1resok()
        data.idl_domains = self.unpack_array(self.unpack_probe_id_domain1)
        if len(data.idl_domains) > 64 and self.check_array:
            raise XDRError('array length too long for data.idl_domains')
        if hasattr(self, 'filter_IDENTITY_DOMAIN_LIST1resok'):
            data = getattr(self, 'filter_IDENTITY_DOMAIN_LIST1resok')(data)
        return data

    def unpack_IDENTITY_DOMAIN_LIST1res(self):
        data = types.IDENTITY_DOMAIN_LIST1res()
        data.idl_status = self.unpack_probe_stat1()
        if data.idl_status == const.PROBE1_OK:
            data.idl_resok = self.unpack_IDENTITY_DOMAIN_LIST1resok()
        else:
            pass
        if hasattr(self, 'filter_IDENTITY_DOMAIN_LIST1res'):
            data = getattr(self, 'filter_IDENTITY_DOMAIN_LIST1res')(data)
        return data

    def unpack_probe_id_mapping1(self):
        data = types.probe_id_mapping1()
        data.pim_from = self.unpack_uint64_t()
        data.pim_to = self.unpack_uint64_t()
        data.pim_name = self.unpack_string()
        if len(data.pim_name) > 256 and self.check_array:
            raise XDRError('array length too long for data.pim_name')
        if hasattr(self, 'filter_probe_id_mapping1'):
            data = getattr(self, 'filter_probe_id_mapping1')(data)
        return data

    def unpack_IDENTITY_MAP_LIST1resok(self):
        data = types.IDENTITY_MAP_LIST1resok()
        data.iml_mappings = self.unpack_array(self.unpack_probe_id_mapping1)
        if len(data.iml_mappings) > 1024 and self.check_array:
            raise XDRError('array length too long for data.iml_mappings')
        if hasattr(self, 'filter_IDENTITY_MAP_LIST1resok'):
            data = getattr(self, 'filter_IDENTITY_MAP_LIST1resok')(data)
        return data

    def unpack_IDENTITY_MAP_LIST1res(self):
        data = types.IDENTITY_MAP_LIST1res()
        data.iml_status = self.unpack_probe_stat1()
        if data.iml_status == const.PROBE1_OK:
            data.iml_resok = self.unpack_IDENTITY_MAP_LIST1resok()
        else:
            pass
        if hasattr(self, 'filter_IDENTITY_MAP_LIST1res'):
            data = getattr(self, 'filter_IDENTITY_MAP_LIST1res')(data)
        return data

    def unpack_IDENTITY_MAP_REMOVE1args(self):
        data = types.IDENTITY_MAP_REMOVE1args()
        data.imr_from = self.unpack_uint64_t()
        if hasattr(self, 'filter_IDENTITY_MAP_REMOVE1args'):
            data = getattr(self, 'filter_IDENTITY_MAP_REMOVE1args')(data)
        return data

