/*
 * SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * AUTO-GENERATED by gen_nfsv42_names.py — DO NOT EDIT BY HAND.
 * Regenerate with:
 *   make gen-names   (or see scripts/gen_nfsv42_names.py --help)
 */

#ifndef NFSV42_NAMES_H
#define NFSV42_NAMES_H

#include <stdint.h>

/* Maximum values for each named group */
#define OP_MAX (OP_CHUNK_WRITE_REPAIR + 1)
#define CB_MAX (OP_CB_OFFLOAD + 1)
#define FATTR4_ATTRIBUTE_MAX FATTR4_CODING_BLOCK_SIZE
#define OPEN4_SHARE_MAX OPEN4_SHARE_ACCESS_WANT_OPEN_XOR_DELEGATION
#define OPEN4_MAX OPEN4_SHARE_ACCESS_WANT_OPEN_XOR_DELEGATION
#define ACCESS4_MAX ACCESS4_XALIST
#define ACL4_MAX ACL4_SUPPORT_ALARM_ACL
#define MODE4_MAX MODE4_SUID
#define RCA4_TYPE_MASK_MAX RCA4_TYPE_MASK_FFV2_LAYOUT_MAX
#define SEQ4_STATUS_MAX SEQ4_STATUS_DEVID_DELETED
#define LAYOUT4_MAX LAYOUT4_RET_REC_ALL
#define NFL4_MAX NFL4_UFLG_STRIPE_UNIT_SIZE_MASK
#define FF_FLAGS_MAX FF_FLAGS_NO_READ_IO
#define EXCHGID4_FLAG_MAX EXCHGID4_FLAG_CONFIRMED_R
#define CREATE_SESSION4_FLAG_MAX CREATE_SESSION4_FLAG_CONN_RDMA

const char *nfs4_err_name(uint32_t v);
const char *nfs4_op_name(uint32_t v);
const char *nfs4_cb_op_name(uint32_t v);
const char *nfs4_layout_type_name(uint32_t v);
const char *nfs4_ftype_name(uint32_t v);
const char *open_claim_type4_name(uint32_t v);
const char *open_delegation_type4_name(uint32_t v);
const char *stable_how4_name(uint32_t v);
const char *createmode4_name(uint32_t v);
const char *opentype4_name(uint32_t v);
const char *limit_by4_name(uint32_t v);
const char *layoutiomode4_name(uint32_t v);
const char *fattr4_name(uint32_t v);
const char *open4_share_name(uint32_t v);
const char *open4_name(uint32_t v);
const char *access4_name(uint32_t v);
const char *acl4_name(uint32_t v);
const char *mode4_name(uint32_t v);
const char *rca4_type_mask_name(uint32_t v);
const char *seq4_status_name(uint32_t v);
const char *layout4_name(uint32_t v);
const char *nfl4_name(uint32_t v);
const char *ff_flags_name(uint32_t v);
const char *exchgid4_flag_name(uint32_t v);
const char *create_session4_flag_name(uint32_t v);
const char *acl4_support_name(uint32_t v);
const char *cb_name(uint32_t v);
const char *exchgid4_flag_supp_name(uint32_t v);
const char *exchgid4_flag_use_name(uint32_t v);
const char *fattr4_case_name(uint32_t v);
const char *fattr4_change_name(uint32_t v);
const char *fattr4_files_name(uint32_t v);
const char *fattr4_fs_name(uint32_t v);
const char *fattr4_layout_name(uint32_t v);
const char *fattr4_mode_name(uint32_t v);
const char *fattr4_quota_name(uint32_t v);
const char *fattr4_quota_avail_name(uint32_t v);
const char *fattr4_retentevt_name(uint32_t v);
const char *fattr4_retention_name(uint32_t v);
const char *fattr4_space_name(uint32_t v);
const char *fattr4_time_name(uint32_t v);
const char *fattr4_time_deleg_name(uint32_t v);
const char *fattr4_uncacheable_name(uint32_t v);
const char *ff_flags_no_name(uint32_t v);
const char *layout4_ret_name(uint32_t v);
const char *layout4_ret_rec_name(uint32_t v);
const char *nfl4_uflg_name(uint32_t v);
const char *open4_result_name(uint32_t v);
const char *open4_share_access_name(uint32_t v);
const char *open4_share_deny_name(uint32_t v);
const char *seq4_status_cb_name(uint32_t v);
const char *seq4_status_devid_name(uint32_t v);
const char *seq4_status_expired_name(uint32_t v);

#endif /* NFSV42_NAMES_H */
