/* SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com> */
/* SPDX-License-Identifier: AGPL-3.0-or-later */

#ifdef HAVE_CONFIG_H
#include "config.h" // IWYU pragma: keep
#endif

/*
 * Reed-Solomon erasure encoding over GF(2^8).
 *
 * Uses a Vandermonde encoding matrix normalized so that the top k rows
 * form the identity.  This makes encoding systematic: data shards pass
 * through unchanged, and only the parity sub-matrix is needed to
 * compute parity shards.
 *
 * Decoding selects k rows corresponding to k available shards, inverts
 * that sub-matrix, and multiplies by the available shard data to
 * recover the original k data shards.  Missing parity shards are then
 * regenerated by re-encoding.
 *
 * Reference: Reed & Solomon, "Polynomial Codes over Certain Finite
 *            Fields" (1960).
 *            Peterson & Weldon, "Error-Correcting Codes" (1972).
 */

#include "reffs/ec.h"

#include <errno.h>
#include <stdlib.h>
#include <string.h>

#include "gf.h"
#include "matrix.h"

struct rs_private {
	struct gf_matrix *rsp_encode; /* (k+m) x k encoding matrix */
	struct gf_matrix *rsp_parity; /* m x k parity sub-matrix */
	/*
	 * Precomputed multiplication tables for every parity
	 * coefficient: parity_tbl[(i * k + j) * 256 + b] ==
	 * gf_mul(rsp_parity[i][j], b).  Built once at create time so
	 * the encode hot path replaces `gf_exp[gf_log[coeff] +
	 * gf_log[b]]` (two table lookups per gf_mul) with a single
	 * direct table lookup.  m * k * 256 bytes; ~8 KiB at k=4 m=2,
	 * ~64 KiB at k=8 m=4 -- well within L1/L2 for realistic
	 * geometries.
	 */
	uint8_t *parity_tbl;
};

/*
 * Build the normalized encoding matrix.
 *
 * Start with a (k+m) x k Vandermonde matrix, then left-multiply by
 * the inverse of its top k x k sub-matrix.  The result has an
 * identity block on top (rows 0..k-1) and the parity generation
 * matrix on the bottom (rows k..k+m-1).
 */
static struct gf_matrix *build_encoding_matrix(int k, int m)
{
	struct gf_matrix *vand = NULL;
	struct gf_matrix *top = NULL;
	struct gf_matrix *top_inv = NULL;
	struct gf_matrix *enc = NULL;

	vand = gf_matrix_vandermonde(k + m, k);
	if (!vand)
		return NULL;

	/* Extract top k x k sub-matrix. */
	top = gf_matrix_create(k, k);
	if (!top)
		goto fail;
	for (int r = 0; r < k; r++)
		for (int c = 0; c < k; c++)
			gf_matrix_set(top, r, c, gf_matrix_get(vand, r, c));

	/* Invert it. */
	top_inv = gf_matrix_create(k, k);
	if (!top_inv)
		goto fail;
	if (gf_matrix_invert(top, top_inv) < 0)
		goto fail;

	/* Multiply: enc = vand * top_inv --> identity on top. */
	enc = gf_matrix_create(k + m, k);
	if (!enc)
		goto fail;
	if (gf_matrix_mul(vand, top_inv, enc) < 0) {
		gf_matrix_destroy(enc);
		enc = NULL;
	}

fail:
	gf_matrix_destroy(vand);
	gf_matrix_destroy(top);
	gf_matrix_destroy(top_inv);
	return enc;
}

static int rs_encode(struct ec_encoding *encoding, uint8_t **data,
		     uint8_t **parity, size_t shard_len)
{
	struct rs_private *rsp = encoding->ec_private;
	int k = encoding->ec_k;
	int m = encoding->ec_m;

	/*
	 * Loop nest ordered i (parity) -> j (data) -> p (byte) rather
	 * than the naive p -> i -> j.  For each (i, j) coefficient we
	 * fix a 256-byte multiplication table pointer once and stream
	 * across all shard_len bytes -- one table lookup per byte, no
	 * per-iteration gf_mul.  Parity buffers are init'd on j == 0
	 * and XOR-accumulated on j > 0.
	 */
	for (int i = 0; i < m; i++) {
		uint8_t *pi = parity[i];

		for (int j = 0; j < k; j++) {
			const uint8_t *tbl =
				&rsp->parity_tbl[(i * k + j) * 256];
			const uint8_t *dj = data[j];

			if (j == 0) {
				for (size_t p = 0; p < shard_len; p++)
					pi[p] = tbl[dj[p]];
			} else {
				for (size_t p = 0; p < shard_len; p++)
					pi[p] ^= tbl[dj[p]];
			}
		}
	}

	return 0;
}

static int rs_decode(struct ec_encoding *encoding, uint8_t **shards,
		     const bool *present, size_t shard_len)
{
	struct rs_private *rsp = encoding->ec_private;
	int k = encoding->ec_k;
	int m = encoding->ec_m;
	int n = k + m;
	int ret = 0;

	/* Count present shards. */
	int avail = 0;

	for (int i = 0; i < n; i++)
		if (present[i])
			avail++;

	if (avail < k)
		return -EIO; /* unrecoverable */

	if (avail == n)
		return 0; /* nothing to reconstruct */

	/*
	 * Build a k x k sub-matrix from the encoding matrix rows
	 * corresponding to the first k available shards.
	 */
	int *avail_idx = calloc((size_t)k, sizeof(int));
	struct gf_matrix *sub = NULL;
	struct gf_matrix *sub_inv = NULL;
	uint8_t **recovered = NULL;

	if (!avail_idx)
		return -ENOMEM;

	int cnt = 0;

	for (int i = 0; i < n && cnt < k; i++) {
		if (present[i])
			avail_idx[cnt++] = i;
	}

	sub = gf_matrix_create(k, k);
	sub_inv = gf_matrix_create(k, k);
	if (!sub || !sub_inv) {
		ret = -ENOMEM;
		goto out;
	}

	for (int r = 0; r < k; r++)
		for (int c = 0; c < k; c++)
			gf_matrix_set(sub, r, c,
				      gf_matrix_get(rsp->rsp_encode,
						    avail_idx[r], c));

	ret = gf_matrix_invert(sub, sub_inv);
	if (ret < 0)
		goto out;

	/*
	 * Precompute a decode-side mul-table for every (row, col) of
	 * sub_inv: decode_tbl[(r * k + c) * 256 + b] = gf_mul(sub_inv[r][c], b).
	 * Amortizes k * k gf_mul_tbl_init calls (~k^2 * 256 =
	 * k^2 * 256 bytes plus init) over the shard_len byte stream.
	 * Break-even is well below the shortest realistic shard.
	 */
	uint8_t *decode_tbl = calloc((size_t)k * (size_t)k * 256, 1);

	if (!decode_tbl) {
		ret = -ENOMEM;
		goto out;
	}
	for (int r = 0; r < k; r++)
		for (int c = 0; c < k; c++)
			gf_mul_tbl_init(gf_matrix_get(sub_inv, r, c),
					&decode_tbl[(r * k + c) * 256]);

	/*
	 * Recover original data shards: multiply sub_inv by the
	 * k available shard data vectors.  Loop nest r -> c -> p
	 * lets us keep a per-(r, c) 256-byte table pointer in a
	 * register across the byte stream.
	 */
	recovered = calloc((size_t)k, sizeof(uint8_t *));
	if (!recovered) {
		free(decode_tbl);
		ret = -ENOMEM;
		goto out;
	}

	for (int i = 0; i < k; i++) {
		recovered[i] = calloc(shard_len, 1);
		if (!recovered[i]) {
			free(decode_tbl);
			ret = -ENOMEM;
			goto out;
		}
	}

	for (int r = 0; r < k; r++) {
		uint8_t *rr = recovered[r];

		for (int c = 0; c < k; c++) {
			const uint8_t *tbl = &decode_tbl[(r * k + c) * 256];
			const uint8_t *sc = shards[avail_idx[c]];

			if (c == 0) {
				for (size_t p = 0; p < shard_len; p++)
					rr[p] = tbl[sc[p]];
			} else {
				for (size_t p = 0; p < shard_len; p++)
					rr[p] ^= tbl[sc[p]];
			}
		}
	}
	free(decode_tbl);

	/* Copy recovered data into missing data shard slots. */
	for (int i = 0; i < k; i++) {
		if (!present[i])
			memcpy(shards[i], recovered[i], shard_len);
	}

	/* Regenerate any missing parity shards by re-encoding. */
	bool need_parity = false;

	for (int i = k; i < n; i++) {
		if (!present[i]) {
			need_parity = true;
			break;
		}
	}

	if (need_parity) {
		/*
		 * Use the now-complete data shards to re-encode.
		 * Reuse rsp->parity_tbl (precomputed at create time)
		 * so this path is the same speed as the forward
		 * encode path.
		 */
		uint8_t **data_ptrs = calloc((size_t)k, sizeof(uint8_t *));

		if (!data_ptrs) {
			ret = -ENOMEM;
			goto out;
		}

		for (int i = 0; i < k; i++)
			data_ptrs[i] = present[i] ? shards[i] : recovered[i];

		uint8_t **parity_ptrs = shards + k;

		for (int i = 0; i < m; i++) {
			if (present[k + i])
				continue;
			uint8_t *pi = parity_ptrs[i];

			for (int j = 0; j < k; j++) {
				const uint8_t *tbl =
					&rsp->parity_tbl[(i * k + j) * 256];
				const uint8_t *dj = data_ptrs[j];

				if (j == 0) {
					for (size_t p = 0; p < shard_len; p++)
						pi[p] = tbl[dj[p]];
				} else {
					for (size_t p = 0; p < shard_len; p++)
						pi[p] ^= tbl[dj[p]];
				}
			}
		}

		free(data_ptrs);
	}

out:
	if (recovered) {
		for (int i = 0; i < k; i++)
			free(recovered[i]);
		free(recovered);
	}
	gf_matrix_destroy(sub);
	gf_matrix_destroy(sub_inv);
	free(avail_idx);
	return ret;
}

struct ec_encoding *ec_rs_create(int k, int m)
{
	struct ec_encoding *encoding = NULL;
	struct rs_private *rsp = NULL;

	if (k < 1 || m < 1 || k + m > 255)
		return NULL;

	gf_init();

	encoding = calloc(1, sizeof(*encoding));
	if (!encoding)
		return NULL;

	rsp = calloc(1, sizeof(*rsp));
	if (!rsp)
		goto fail;

	rsp->rsp_encode = build_encoding_matrix(k, m);
	if (!rsp->rsp_encode)
		goto fail;

	/* Extract the parity sub-matrix (bottom m rows). */
	rsp->rsp_parity = gf_matrix_create(m, k);
	if (!rsp->rsp_parity)
		goto fail;

	for (int r = 0; r < m; r++)
		for (int c = 0; c < k; c++)
			gf_matrix_set(rsp->rsp_parity, r, c,
				      gf_matrix_get(rsp->rsp_encode, k + r, c));

	/*
	 * Precompute per-coefficient 256-byte multiplication tables
	 * for every (i, j) of the parity sub-matrix.  This is the
	 * single-largest scalar-speedup for rs_encode: swap the
	 * per-byte gf_exp[gf_log[coeff] + gf_log[b]] double-lookup
	 * for a one-step table[coeff][b] lookup, keeping the table
	 * pointer in a register across the whole shard_len byte
	 * stream.
	 */
	rsp->parity_tbl = calloc((size_t)m * (size_t)k * 256, 1);
	if (!rsp->parity_tbl)
		goto fail;
	for (int r = 0; r < m; r++)
		for (int c = 0; c < k; c++)
			gf_mul_tbl_init(gf_matrix_get(rsp->rsp_parity, r, c),
					&rsp->parity_tbl[(r * k + c) * 256]);

	encoding->ec_name = "reed-solomon";
	encoding->ec_k = k;
	encoding->ec_m = m;
	encoding->ec_encode = rs_encode;
	encoding->ec_decode = rs_decode;
	encoding->ec_shard_size = NULL; /* uniform shards */
	encoding->ec_destroy = NULL; /* use default free */
	encoding->ec_private = rsp;

	return encoding;

fail:
	if (rsp) {
		gf_matrix_destroy(rsp->rsp_encode);
		gf_matrix_destroy(rsp->rsp_parity);
		free(rsp->parity_tbl);
		free(rsp);
	}
	free(encoding);
	return NULL;
}

void ec_encoding_destroy(struct ec_encoding *encoding)
{
	if (!encoding)
		return;

	if (encoding->ec_destroy) {
		encoding->ec_destroy(encoding);
		return;
	}

	/* Default: RS cleanup. */
	struct rs_private *rsp = encoding->ec_private;

	if (rsp) {
		gf_matrix_destroy(rsp->rsp_encode);
		gf_matrix_destroy(rsp->rsp_parity);
		free(rsp->parity_tbl);
		free(rsp);
	}
	free(encoding);
}
