#!/bin/sh

# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

# Change to the root directory of the Git repository
git rev-parse --show-toplevel > /dev/null 2>&1 || exit 1
ROOT_DIR=$(git rev-parse --show-toplevel)
cd "$ROOT_DIR"

# Execute the pre-commit build
make -f Makefile.reffs reconf

# Check the exit status of the make command
if [ $? -ne 0 ]; then
    echo "Pre-commit Autoconf failed. Aborting commit."
    exit 1
fi

# Execute the style check
make -f Makefile.reffs style

# Check the exit status of the make command
if [ $? -ne 0 ]; then
    echo "Pre-commit Style check failed. Run 'make -f Makefile.reffs fix-style' to fix it."
    exit 1
fi

# Execute the license check
make -f Makefile.reffs license

# Check the exit status of the make command
if [ $? -ne 0 ]; then
    echo "Pre-commit License check failed. Run './check_license.sh' for details."
    exit 1
fi

# Now build out of tree

./tree-build.sh
if [ $? -ne 0 ]; then
    echo "Pre-commit Out-of-tree build failed. Aborting commit."
    exit 1
fi

# Check if the commit message contains a "Signed-off-by" line
# Note: In a pre-commit hook, the commit message is not yet in the log.
# This check is more reliably done in a commit-msg hook, but we can 
# check the staged changes' sign-off if we are just verifying the policy.
# However, the standard DCO check for pre-commit is often omitted in favor 
# of a commit-msg hook. For now, let's fix it to look at the message if provided,
# but usually, we'd want to check the message file.

if [ -f .git/COMMIT_EDITMSG ]; then
    if ! grep -q "^Signed-off-by:" .git/COMMIT_EDITMSG; then
        echo "Error: Commit message must contain a 'Signed-off-by:' line."
        echo "Use 'git commit -s' or manually add a 'Signed-off-by:' line to your commit message."
        exit 1
    fi
fi

exit 0
