#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# gen_nfsv42_names.py — generate nfsv42_names.{c,h} from nfsv42_xdr.x
#                       and (optionally) the rpcgen-produced nfsv42_xdr.h.
#
# Usage:
#   python3 gen_nfsv42_names.py \
#       --xdr  lib/xdr/nfsv42_xdr.x   \
#       --hdr  lib/xdr/nfsv42_xdr.h   \
#       --out  lib/nfs4
#
# What it extracts:
#
#   From the .x file:
#     enum  blocks          → one name-table + lookup function per enum
#     const groups          → contiguous consts sharing a prefix get a table
#                             (NFS4ERR_*, OPEN4_*, OP_*, CB_*, FATTR4_*, …)
#
#   From the .h file (rpcgen output):
#     #define NAME value    → fills in any gaps left by the .x parser,
#                             e.g. FATTR4_* which rpcgen renders as #defines
#                             rather than keeping them as enum members.
#
# The script is conservative: it only generates a table when it finds at
# least 2 members with the same prefix and consecutive-ish numeric values.
# Sparse enums (e.g. nfsstat4 error codes) use a hash-based fallback that
# stores only the (value, name) pairs that exist.

import argparse
import re
import sys
import os
from collections import defaultdict
from pathlib import Path

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

SPDX_C = """\
/*
 * SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * AUTO-GENERATED by gen_nfsv42_names.py — DO NOT EDIT BY HAND.
 * Regenerate with:
 *   make gen-names   (or see scripts/gen_nfsv42_names.py --help)
 */
"""

def eval_const(s):
    """Parse a decimal, hex, or octal integer string."""
    s = s.strip()
    try:
        return int(s, 0)
    except ValueError:
        return None


def common_prefix(names):
    """Return the longest shared prefix ending at '_', or '' if none."""
    if not names:
        return ''
    prefix = os.path.commonprefix(names)
    idx = prefix.rfind('_')
    return prefix[:idx + 1] if idx >= 0 else ''


def is_dense_enough(values, threshold=0.5):
    """
    Return True if the values are dense enough to warrant a flat array.
    Threshold: filled fraction of [min..max] range.
    """
    if len(values) < 2:
        return True
    lo, hi = min(values), max(values)
    span = hi - lo + 1
    return len(values) / span >= threshold


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------

def parse_xdr_enums(xdr_text):
    text = re.sub(r'/\*.*?\*/', ' ', xdr_text, flags=re.DOTALL)
    text = re.sub(r'//[^\n]*', ' ', text)
    text = re.sub(r'^\s*%[^\n]*', ' ', text, flags=re.MULTILINE)

    enums = {}
    for m in re.finditer(r'\benum\s+(\w+)\s*\{([^}]*)\}', text, re.DOTALL):
        etype = m.group(1)
        body  = m.group(2)
        members = []
        counter = 0
        for item in re.split(r',', body):
            item = item.strip()
            if not item:
                continue
            eq = re.match(r'(\w+)\s*=\s*(-?(?:0[xX][0-9a-fA-F]+|\d+))\s*$', item)
            if eq:
                name = eq.group(1)
                val  = eval_const(eq.group(2))
                if val is None:
                    continue
                counter = val
            else:
                name = item if re.fullmatch(r'\w+', item) else None
                if not name:
                    continue
            members.append((name, counter))
            counter += 1
        if members:
            enums[etype] = members
    return enums


def parse_xdr_consts(xdr_text):
    """
    Extract all   const NAME = value;   lines.
    Returns list of (name, value) in source order.
    """
    text = re.sub(r'/\*.*?\*/', ' ', xdr_text, flags=re.DOTALL)
    text = re.sub(r'//[^\n]*', ' ', text)
    consts = []
    for m in re.finditer(r'\bconst\s+(\w+)\s*=\s*([^;]+);', text):
        name = m.group(1)
        val  = eval_const(m.group(2))
        if val is not None:
            consts.append((name, val))
    return consts


def parse_header_defines(hdr_text):
    """
    Extract   #define NAME value   lines from the rpcgen header.
    Returns list of (name, value) in source order.
    """
    defines = []
    for m in re.finditer(r'^\s*#\s*define\s+(\w+)\s+(0[xX][0-9a-fA-F]+|\d+)\s*$',
                         hdr_text, re.MULTILINE):
        name = m.group(1)
        val  = eval_const(m.group(2))
        if val is not None:
            defines.append((name, val))
    return defines


def group_by_prefix(items):
    """
    items: list of (name, value)
    Returns dict: prefix -> list of (name, value), keeping only groups
    with >= 2 members.
    """
    by_prefix = defaultdict(list)
    for name, val in items:
        # Walk from longest possible prefix down to the first '_'
        parts = name.split('_')
        for end in range(len(parts) - 1, 0, -1):
            pfx = '_'.join(parts[:end]) + '_'
            by_prefix[pfx].append((name, val))
    # Keep only groups that have >= 2 distinct values
    return {k: v for k, v in by_prefix.items()
            if len({vv for _, vv in v}) >= 2}


# ---------------------------------------------------------------------------
# Code generators
# ---------------------------------------------------------------------------

def make_func_name(prefix_or_type):
    """Turn FATTR4_ or nfsstat4 into a C identifier like fattr4_name."""
    s = prefix_or_type.lower().rstrip('_')
    # nfsstat4 → nfs4_err_name  (keep the existing reffs convention)
    aliases = {
        'nfsstat4':     'nfs4_err',
        'nfs_opnum4':   'nfs4_op',
        'nfs_cb_opnum4':'nfs4_cb_op',
        'layouttype4':  'nfs4_layout_type',
    }
    return aliases.get(s, s) + '_name'


MAX_NAME_OVERRIDES = {
    'FATTR4': 'FATTR4_ATTRIBUTE_MAX',
    'NFS4ERR': 'NFS4ERR_MAX',
    'OP': 'OP_MAX',
    'CB': 'CB_MAX',
}

def max_define(prefix, members):
    """
    Return a (define_name, symbol) pair for the highest-valued member,
    e.g. ('FATTR4_ATTRIBUTE_MAX', 'FATTR4_UNCACHEABLE').
    Returns None for bare enum types with no usable prefix.
    """
    p = prefix.rstrip('_')
    if not p or not p[0].isupper():
        return None
    top_name = max(members, key=lambda x: x[1])[0]
    define_name = MAX_NAME_OVERRIDES.get(p, f'{p}_MAX')
    return (define_name, top_name)


def render_dense_table(prefix, members, func_name):
    """Flat array indexed by value; symbolic names used throughout."""
    values = [v for _, v in members]
    lo, hi = min(values), max(values)

    val2name = {v: n for n, v in members}
    lo_sym = val2name[lo]
    hi_sym = val2name[hi]

    tbl = f'{prefix.lower().rstrip("_")}_names'
    lines_c = []
    lines_c.append(f'static const char * const {tbl}[] = {{')
    for v in range(lo, hi + 1):
        if v in val2name:
            sym = val2name[v]
            lines_c.append(f'\t[{sym} - {lo_sym}] = "{sym}",')
        else:
            lines_c.append(f'\t/* gap at {v} */')
    lines_c.append('};')
    lines_c.append('')

    lines_c.append(f'const char *{func_name}(uint32_t v)')
    lines_c.append('{')
    lines_c.append(f'\tif (v < (uint32_t){lo_sym} || v > (uint32_t){hi_sym})')
    lines_c.append(f'\t\treturn "{prefix}_UNKNOWN";')
    lines_c.append(f'\tconst char *n = {tbl}[v - {lo_sym}];')
    lines_c.append(f'\treturn n ? n : "{prefix}_UNKNOWN";')
    lines_c.append('}')

    decl = f'const char *{func_name}(uint32_t v);'
    mx   = max_define(prefix, members)
    return '\n'.join(lines_c), decl, mx


def render_sparse_table(prefix, members, func_name):
    """Linear-search table for sparse value spaces (e.g. NFS4ERR_*)."""
    tbl_name = f'{prefix.lower().rstrip("_")}_tbl'
    lines_c  = []

    lines_c.append(f'static const struct {{ uint32_t v; const char *n; }}')
    lines_c.append(f'{tbl_name}[] = {{')
    for name, val in sorted(members, key=lambda x: x[1]):
        lines_c.append(f'\t{{ (uint32_t){name}, "{name}" }},')
    lines_c.append('};')
    lines_c.append('')
    lines_c.append(f'const char *{func_name}(uint32_t v)')
    lines_c.append('{')
    lines_c.append(f'\tfor (size_t i = 0; i < sizeof({tbl_name})/sizeof({tbl_name}[0]); i++)')
    lines_c.append(f'\t\tif ({tbl_name}[i].v == v)')
    lines_c.append(f'\t\t\treturn {tbl_name}[i].n;')
    lines_c.append(f'\treturn "{prefix}_UNKNOWN";')
    lines_c.append('}')

    decl = f'const char *{func_name}(uint32_t v);'
    mx   = max_define(prefix, members)
    return '\n'.join(lines_c), decl, mx


def render_group(prefix_or_type, members, func_name):
    values = [v for _, v in members]
    if is_dense_enough(values):
        return render_dense_table(prefix_or_type, members, func_name)
    else:
        return render_sparse_table(prefix_or_type, members, func_name)


# ---------------------------------------------------------------------------
# Decide which const groups to emit
# ---------------------------------------------------------------------------

# Prefixes we specifically want, in the order we want them in the output.
# Each tuple: (prefix_in_source, func_name_override_or_None)
WANTED_CONST_PREFIXES = [
    ('FATTR4_',          'fattr4_name'),
    ('OP_',              'nfs4_op_name'),       # OP_ACCESS etc. from nfs_opnum4
    ('CB_',              'nfs4_cb_op_name'),
    ('OPEN4_SHARE_',     None),
    ('OPEN4_',           None),
    ('LOCK4_',           None),
    ('ACCESS4_',         None),
    ('ACL4_',            None),
    ('MODE4_',           None),
    ('RPCSEC_GSS_',      None),
    ('RCA4_TYPE_MASK_',  None),
    ('SEQ4_STATUS_',     None),
    ('LAYOUT4_',         None),
    ('NFL4_',            None),
    ('FF_FLAGS_',        None),
    ('EXCHGID4_FLAG_',   None),
    ('CREATE_SESSION4_FLAG_', None),
    ('BIND_CONN_TO_SESSION4_', None),
]

# Enum type names we want (maps xdr type name → func name override or None).
WANTED_ENUMS = {
    'nfsstat4':           'nfs4_err_name',
    'nfs_opnum4':         'nfs4_op_name',
    'nfs_cb_opnum4':      'nfs4_cb_op_name',
    'layouttype4':        'nfs4_layout_type_name',
    'nfs_ftype4':         'nfs4_ftype_name',
    'open_claim_type4':   None,
    'open_delegation_type4': None,
    'lock_type4':         None,
    'stable_how4':        None,
    'createmode4':        None,
    'opentype4':          None,
    'limit_by4':          None,
    'direction_how4':     None,
    'rpc_gss_svc_t':      None,
    'gss_union_t':        None,
    'layoutiomode4':      None,
    'nfs4_content_type':  None,
}


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(
        description='Generate nfsv42_names.{c,h} from nfsv42_xdr.x')
    ap.add_argument('--xdr', required=True,
                    help='Path to nfsv42_xdr.x')
    ap.add_argument('--hdr', default=None,
                    help='Path to rpcgen-produced nfsv42_xdr.h (optional)')
    ap.add_argument('--out', default='.',
                    help='Output directory (default: .)')
    args = ap.parse_args()

    xdr_text = Path(args.xdr).read_text()
    hdr_text = Path(args.hdr).read_text() if args.hdr else ''

    out_dir  = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Collect raw material
    # ------------------------------------------------------------------
    xdr_enums  = parse_xdr_enums(xdr_text)
    xdr_consts = parse_xdr_consts(xdr_text)
    hdr_defs   = parse_header_defines(hdr_text)

    # All defines: xdr consts first, then header defines (header wins on dup)
    all_defs = {}
    for name, val in xdr_consts + hdr_defs:
        all_defs[name] = val   # last write wins
    all_defs_list = list(all_defs.items())

    # ------------------------------------------------------------------
    # Build the list of (func_name, members, prefix_or_type) to emit,
    # deduplicating: enums take priority over const groups.
    # ------------------------------------------------------------------
    emitted_func_names = set()
    groups = []   # list of (func_name, members, label_for_comment)

    # 1. Named enums we care about
    for etype, override_func in WANTED_ENUMS.items():
        if etype not in xdr_enums:
            continue
        func = override_func or make_func_name(etype)
        if func in emitted_func_names:
            continue
        emitted_func_names.add(func)
        groups.append((func, xdr_enums[etype], etype, False))

    # 2. Const prefix groups
    all_defs_list = [(n, v) for n, v in all_defs.items()
                     if 0 <= v <= 0xFFFFFFFF]
    const_by_prefix = group_by_prefix(all_defs_list)
    for prefix, override_func in WANTED_CONST_PREFIXES:
        if prefix not in const_by_prefix:
            continue
        func = override_func or make_func_name(prefix)
        if func in emitted_func_names:
            continue
        emitted_func_names.add(func)
        groups.append((func, const_by_prefix[prefix], prefix, True))

    # 3. Anything else with >= 2 members that has a recognisable NFSv4 prefix
    auto_prefixes = {k for k in const_by_prefix
                 if re.match(r'^(NFS4ERR_|FATTR4_|OP_|CB_|ACCESS4_|OPEN4_|LOCK4_|'
                             r'ACL4_|MODE4_|SEQ4_STATUS_|LAYOUT4_|NFL4_|FF_FLAGS_|'
                             r'EXCHGID4_FLAG_|CREATE_SESSION4_FLAG_|RCA4_TYPE_MASK_)', k)
                 and k.count('_') <= 3}   # ← cap depth
    for prefix in sorted(auto_prefixes):
        func = make_func_name(prefix)
        if func in emitted_func_names:
            continue
        emitted_func_names.add(func)
        groups.append((func, const_by_prefix[prefix], prefix, False))

    # ------------------------------------------------------------------
    # Render
    # ------------------------------------------------------------------
    c_sections = []
    h_decls    = []
    h_maxes    = []   # list of (define_name, symbol) pairs

    for func_name, members, label, emit_max in groups:
        # Deduplicate members (same value, keep first name)
        seen_vals = {}
        deduped = []
        for name, val in members:
            if val not in seen_vals:
                seen_vals[val] = name
                deduped.append((name, val))

        c_body, h_decl, mx = render_group(label, deduped, func_name)
        c_sections.append(f'/* {label} */\n{c_body}')
        h_decls.append(h_decl)
        if mx and emit_max:
            h_maxes.append(mx)

    # ------------------------------------------------------------------
    # Write .c
    # ------------------------------------------------------------------
    c_path = out_dir / 'nfsv42_names.c'
    with c_path.open('w') as f:
        f.write(SPDX_C)
        f.write('\n')
        f.write('#include <stddef.h>\n')
        f.write('#include <stdint.h>\n')
        f.write('\n')
        f.write('#include "nfsv42_xdr.h"\n')
        f.write('#include "nfsv42_names.h"\n')
        f.write('\n')
        for section in c_sections:
            f.write(section)
            f.write('\n\n')
    print(f'Wrote {c_path}')

    # ------------------------------------------------------------------
    # Write .h
    # ------------------------------------------------------------------
    h_path = out_dir / 'nfsv42_names.h'
    guard  = 'NFSV42_NAMES_H'
    with h_path.open('w') as f:
        f.write(SPDX_C)
        f.write(f'\n#ifndef {guard}\n#define {guard}\n\n')
        f.write('#include <stdint.h>\n\n')
        # _MAX defines — e.g. #define FATTR4_ATTRIBUTE_MAX FATTR4_UNCACHEABLE
        if h_maxes:
            f.write('/* Maximum values for each named group */\n')
            for define_name, symbol in h_maxes:
                f.write(f'#define {define_name} {symbol}\n')
            f.write('\n')
        for decl in h_decls:
            f.write(decl + '\n')
        f.write(f'\n#endif /* {guard} */\n')
    print(f'Wrote {h_path}')


if __name__ == '__main__':
    main()
