#!/bin/bash
# SPDX-FileCopyrightText: 2026 Tom Haynes <loghyr@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# run_mds_validate.sh -- Launch reffs as a no-rpcbind Flex Files MDS
# for validating an external NFSv4.2 client.  Bare-metal, no Docker:
# builds reffsd in build/ if needed, then runs it in the foreground.
#
# reffs runs as the MDS ONLY -- the data servers are EXTERNAL and you
# supply them with --ds (repeatable).  rpcbind is disabled
# (register_with_rpcbind = false): NFSv4.2 uses the well-known port
# 2049 (RFC 8881 S1.5) and needs no portmapper.
#
# This script does NOT mount anything.  Mount it yourself from your
# client, e.g.:
#     sudo mount -t nfs -o vers=4.2 <this-host>:/ /mnt/point
#
# Usage:
#   scripts/run_mds_validate.sh [--ds ADDR:/PATH[:NFSPORT[:MOUNTPORT]]]... [OPTIONS]
#
# Options:
#   --ds ADDR:/PATH[:NFSPORT[:MOUNTPORT]]
#                     External data server (repeatable).  ADDR is an
#                     IPv4 address or hostname; PATH is its export path.
#                     NFSPORT (optional) pins the nfsd port; MOUNTPORT
#                     (optional) pins the mountd port.  Both are trailing
#                     all-digit fields.  An explicit NFSPORT also marks
#                     this as a real wire DS, so a link-local or
#                     same-host address (e.g. a knfsd instance) is
#                     contacted over NFSv3 rather than served from the
#                     local combined-mode VFS.
#                       knfsd runs mountd and nfsd on separate ports:
#                       set both, e.g. 169.254.0.5:/exp:3049:20048.
#                       A reffs DS serves both on one port, so NFSPORT
#                       alone suffices.  Omit both ports to use the DS
#                       host's portmap (rpcbind) for discovery.
#                     With no --ds the MDS still boots and is mountable
#                     but issues no layouts (LAYOUTGET ->
#                     NFS4ERR_LAYOUTUNAVAILABLE).
#   --layout TYPES    Comma-separated layout types when --ds is given
#                     (default: ffv1).  ffv1 works with any NFSv3 DS;
#                     ffv2 needs reffs DSes that speak the CHUNK ops.
#   --port N          MDS NFS port (default: 2049).  Must be free on
#                     this host.
#   --data DIR        Runtime data/state/config dir
#                     (default: /tmp/reffs-mds-validate).
#   --rebuild         Force a clean rebuild of reffsd before launch.
#   --dry-run         Generate the config and print it; do not build
#                     or launch.
#   -h, --help        Show this help and exit.
#
# Prerequisites: build dependencies installed (clang, xdr-parser,
# liburcu, libtirpc, openssl, libcheck, ...).  Run as your normal
# user, not root.
set -euo pipefail

# -- Defaults (overridable via command line) --
PORT=2049
DATA_DIR="/tmp/reffs-mds-validate"
LAYOUT_TYPES="ffv1"
REBUILD=0
DRY_RUN=0
DS_SPECS=()

usage() { sed -n '4,/^set -euo pipefail/p' "$0" | sed '$d; s/^# \{0,1\}//'; }

while [[ $# -gt 0 ]]; do
	case "$1" in
	--ds)      DS_SPECS+=("$2"); shift 2 ;;
	--layout)  LAYOUT_TYPES="$2"; shift 2 ;;
	--port)    PORT="$2"; shift 2 ;;
	--data)    DATA_DIR="$2"; shift 2 ;;
	--rebuild) REBUILD=1; shift ;;
	--dry-run) DRY_RUN=1; shift ;;
	-h|--help) usage; exit 0 ;;
	*)         echo "Unknown option: $1" >&2; usage; exit 1 ;;
	esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_DIR="$PROJECT_ROOT/build"
REFFSD="$BUILD_DIR/src/reffsd"
CONFIG="$DATA_DIR/reffsd.toml"
TRACE="$DATA_DIR/reffs.trc"

# -- Build reffsd if it is missing (or --rebuild) -------------------
if [[ "$DRY_RUN" != 1 && ( "$REBUILD" == 1 || ! -x "$REFFSD" ) ]]; then
	echo ">> Building reffsd in $BUILD_DIR ..."
	cd "$PROJECT_ROOT"
	mkdir -p m4
	[[ -x ./configure ]] || autoreconf -fi
	mkdir -p "$BUILD_DIR"
	cd "$BUILD_DIR"
	[[ -f Makefile ]] || ../configure
	make -j"$(nproc)"
	cd "$PROJECT_ROOT"
fi
if [[ "$DRY_RUN" != 1 && ! -x "$REFFSD" ]]; then
	echo "reffsd not found at $REFFSD" >&2
	exit 1
fi

# -- Generate the runtime config ------------------------------------
# Generated fresh (not copied from the example) so the data-server
# entries are exactly the reachable DSes you passed -- this avoids the
# startup stall the committed example warns about, where the MDS blocks
# on unreachable placeholder DSes before it begins serving.
mkdir -p "$DATA_DIR/data" "$DATA_DIR/state"

{
	echo "# Generated by run_mds_validate.sh -- safe to delete."
	echo "[server]"
	echo "port                  = $PORT"
	echo 'bind                  = "*"'
	echo 'role                  = "mds"'
	echo "register_with_rpcbind = false"
	echo "minor_versions        = [1, 2]"
	echo "grace_period          = 45"
	echo "workers               = 8"
	echo "max_session_slots     = 64"
	echo 'log_level             = "info"'
	echo
	echo "[backend]"
	echo 'type            = "posix"'
	echo "path            = \"$DATA_DIR/data\""
	echo "state_file      = \"$DATA_DIR/state\""
	echo
	echo "[[export]]"
	echo 'path         = "/"'
	if [[ ${#DS_SPECS[@]} -gt 0 ]]; then
		# layout_types as a TOML array: ["ffv1", "ffv2"]
		lt=""
		IFS=',' read -ra _types <<< "$LAYOUT_TYPES"
		for t in "${_types[@]}"; do lt+="${lt:+, }\"$t\""; done
		echo "layout_types = [$lt]"
		ids=$(seq -s ', ' 1 "${#DS_SPECS[@]}")
		echo "dstores      = [$ids]"
	fi
	echo
	echo "    [[export.clients]]"
	echo '    match       = "*"'
	echo '    access      = "rw"'
	echo "    root_squash = false"
	echo '    flavors     = ["sys"]'
	# One [[data_server]] per --ds.  Split ADDR:/PATH on the first
	# colon (IPv4/hostname has no colon; the path starts with '/'),
	# then peel up to two trailing all-digit ports in the order
	# PATH:NFSPORT:MOUNTPORT (so a path containing a colon is not
	# misread as a port).
	id=0
	for spec in "${DS_SPECS[@]+"${DS_SPECS[@]}"}"; do
		id=$((id + 1))
		addr="${spec%%:*}"
		rest="${spec#*:}"
		nfsport=""
		mountport=""
		if [[ "$rest" == *:* && "${rest##*:}" =~ ^[0-9]+$ ]]; then
			last="${rest##*:}"
			rest="${rest%:*}"
			if [[ "$rest" == *:* && "${rest##*:}" =~ ^[0-9]+$ ]]; then
				mountport="$last"
				nfsport="${rest##*:}"
				path="${rest%:*}"
			else
				nfsport="$last"
				path="$rest"
			fi
		else
			path="$rest"
		fi
		echo
		echo "[[data_server]]"
		echo "id         = $id"
		echo "address    = \"$addr\""
		echo "path       = \"$path\""
		[[ -n "$nfsport" ]] && echo "port       = $nfsport"
		[[ -n "$mountport" ]] && echo "mount_port = $mountport"
	done
} > "$CONFIG"

if [[ "$DRY_RUN" == 1 ]]; then
	echo "(dry-run) generated config at $CONFIG:"
	echo
	cat "$CONFIG"
	exit 0
fi

# -- Launch (foreground; Ctrl-C stops reffsd) -----------------------
echo
echo "==================================================================="
echo " reffs MDS (no rpcbind) for external-client validation"
echo "   port      : $PORT"
echo "   config    : $CONFIG"
echo "   trace     : $TRACE"
echo "   data/state: $DATA_DIR/{data,state}"
if [[ ${#DS_SPECS[@]} -gt 0 ]]; then
	echo "   dstores   : ${DS_SPECS[*]}  (layout_types: $LAYOUT_TYPES)"
else
	echo "   dstores   : none (server boots + mounts, but issues no layouts)"
fi
echo
echo " Mount it from your client (this script will NOT mount):"
echo "   sudo mount -t nfs -o vers=4.2 <this-host>:/ /mnt/point"
echo
echo " Ctrl-C to stop."
echo "==================================================================="
echo
exec "$REFFSD" --file="$TRACE" --config="$CONFIG"
