name: C/C++ CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          pkg-config \
          liburcu-dev \
          libtirpc-dev \
          check \
          libxxhash-dev \
          libfuse-dev \
          rpcsvc-proto \
          uuid-dev \
          zlib1g-dev \
          libzstd-dev \
          liburing-dev \
          libjemalloc-dev \
          python3 \
          python3-pip \
          python3-ply \
          clang-format-18 \
          clang-tidy \
          clang-tools \
          autoconf \
          automake \
          libtool \
          libtool-bin \
          autoconf-archive \
          libssl-dev \
          libcap-dev \
          psmisc \
          valgrind \
          cmake

    - name: Install Python dependencies
      run: pip3 install --no-cache-dir --break-system-packages xdrlib3

    - name: Set environment variables
      run: echo "CLANG_FORMAT=clang-format-18" >> $GITHUB_ENV

    - name: Install HdrHistogram_c
      run: |
        mkdir -p build/deps
        git clone https://github.com/HdrHistogram/HdrHistogram_c.git build/deps/HdrHistogram_c
        cd build/deps/HdrHistogram_c
        mkdir build_dir
        cd build_dir
        cmake ..
        make
        sudo make install
        sudo ldconfig

    - name: Create m4 directory
      run: mkdir -p m4

    - name: Autoreconf
      run: autoreconf -fi

    - name: Check license
      run: SKIP_STYLE=1 make -f Makefile.reffs license

    - name: Configure
      run: ./configure --enable-asan --enable-ubsan

    - name: Build
      run: make -j$(nproc)

    - name: Run tests
      run: make check
